### PR TITLE
Document how etcd's TLS assets are managed

### PR DESCRIPTION
**Pull request by markmc**
I found all of this quite bewildering to keep straight in my head, so I figured I'd try to write it down.

### CODE REVIEW

**Comment by hexfusion** [comment]
@markmc this is an amazing amount of work. Thank you, will review soon.

**Comment by cgwalters** [comment]
I happened to come across this when I was trying to figure out how the etcd static pod manifest is installed.  Agreed, awesome work!  I personally would merge this as is and do other changes as followups to avoid losing it.

It seems though the second half in particular is more about the architecture, and isn't specific to certs; maybe move that into a separate `design.md`?

**Comment by hexfusion** [comment]
yeah let's merge marks work and fine-tune from here thanks again.

**Pull request merged**
