### PR TITLE
OCPBUGS-1329: Add niceness to important etcd processes

### PR DESCRIPTION
**Pull request by tjungblu**
/hold

just want to check whether we can influence the niceness on etcd for CPU as well. This normally requires su privileges.

### CODE REVIEW

**Comment by tjungblu** [comment]
happy news, seems to actually apply on SNO :) 

```
  54388   54376 -20 etcd
  54442       1   0 conmon
  54455   54442 -19 etcd
```

I'll do some load test and brush this up, then we can backport...

**Comment by tjungblu** [comment]
/retitle Add niceness to important etcd processes

**Comment by dusk125** [comment]
lgtm, will approve when we get another lgtm

**Comment by tjungblu** [comment]
/assign @hasbro17 
/assign @EmilyM1  maybe any of you two?

@Elbehery said he wouldn't review

**Comment by tjungblu** [comment]
/retitle OCPBUGS-1329: Add niceness to important etcd processes

**Pull request merged**
