### PR TITLE
Bug 1802228:  For etcd discovery domain, watch infrastructure not controller config

### PR DESCRIPTION
**Pull request by retroflexer**
Moving away from controller config.

### CODE REVIEW

**Comment by hexfusion** [comment]
@retroflexer you need to fix verify

**Comment by retroflexer** [comment]
> @retroflexer you need to fix verify

Thanks. Pushed gofmt fixes.

**Comment by deads2k** [comment]
are the dynamic clients still used?  If not, please remove them.

**Comment by deads2k** [comment]
/approve

but you need to fix dynamic client needs (I think it's cruft) before merge.

**Comment by retroflexer** [comment]
> but you need to fix dynamic client needs (I think it's cruft) before merge.
@deads2k Got rid of dynamicClients.

**Pull request merged**
