### PR TITLE
[WIP] Upgrade library-go version

### PR DESCRIPTION
**Pull request by qJkee**
Bumping the library-go dependency to latest, this should take advantage of leader election changes for SNO clusters proposed in this [library-go PR](https://github.com/openshift/library-go/pull/1242) and performance improvements in this [PR](https://github.com/openshift/library-go/pull/1235).

### CODE REVIEW

**Comment by hexfusion** [comment]
One of the deps breaks the operator 

https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_cluster-etcd-operator/715/pull-ci-openshift-cluster-etcd-operator-master-e2e-agnostic/1470783301974233088/artifacts/e2e-agnostic/gather-extra/artifacts/pods/openshift-etcd-operator_etcd-operator-856887b698-b6s48_etcd-operator.log

**Comment by damemi** [comment]
Hi, just noticed this... you may want to update this PR to bump all of the dependencies (not just library-go) and k8s as well. We have updated our libraries to 1.23, so you'll need to make updates like this https://github.com/openshift/cluster-etcd-operator/pull/716 (feel free to close my PR if you want)

The error @hexfusion pointed out is related to the 1.23 bump, and will need to be fixed with a change similar to this in how logging is initialized: https://github.com/openshift/cluster-kube-controller-manager-operator/pull/581/commits/c339a947622142be4e6e0df7799cb2a1445e1eb2

More info on aos-devel https://mailman-int.corp.redhat.com/archives/aos-devel/2021-December/msg00088.html

**Comment by qJkee** [comment]
> Hi, just noticed this... you ~may want to~ should update this PR to bump all of the dependencies (not just library-go) and k8s as well. We have updated our libraries to 1.23, so you'll need to make updates like this #716 (feel free to close my PR if you want)
> 
> The error @hexfusion pointed out is related to the 1.23 bump, and will need to be fixed with a change similar to this in how logging is initialized: [openshift/cluster-kube-controller-manager-operator@c339a94](https://github.com/openshift/cluster-kube-controller-manager-operator/commit/c339a947622142be4e6e0df7799cb2a1445e1eb2)
> 
> More info on aos-devel https://mailman-int.corp.redhat.com/archives/aos-devel/2021-December/msg00088.html

@damemi all packages are updated as well since it's required by new version of library-go

**Comment by damemi** [comment]
@qJkee ah, sorry.. I didn't actually look at the changes, just assumed from the PR title (my mistake)

However the logging fix I linked should still help you here. I'll close my other PR

**Comment by hexfusion** [comment]
@qJkee I appreciate the PR but as this bump is time sensitive I needed to get it merged. Looks like it's just a dep issue at this point. Sorry and Thanks!

superseded by https://github.com/openshift/cluster-etcd-operator/pull/718

**Pull request closed without merging**
