### PR TITLE
OCPBUGS-11683: Revert Add Controller health to CEO liveness probe

### PR DESCRIPTION
**Pull request by tjungblu**
Reverts openshift/cluster-etcd-operator#1039

to unblock the 4.13 release, I need some more time to test why this fails with SNO.

### CODE REVIEW

**Comment by tjungblu** [comment]
/retitle OCPBUGS-11683: Revert Add Controller health to CEO liveness probe

**Comment by tjungblu** [comment]
@geliu2016 could you kindly CPA this when you're up again, please?

**Review by geliu2016 — APPROVED** [review]
/label cherry-pick-approved

**Comment by tjungblu** [comment]
Overriding the unrelated failures (jobs are optional anyway)

/override ci/prow/e2e-agnostic-ovn-upgrade

/override ci/prow/e2e-aws-ovn-single-node

**Pull request merged**
