### PR TITLE
Bug 1838781: pkg/etcdcli: refactor health checks

### PR DESCRIPTION
**Pull request by hexfusion**
Manual cherry-pick of https://github.com/openshift/cluster-etcd-operator/pull/343

### CODE REVIEW

**Comment by hexfusion** [comment]
build errors..
/retest

**Comment by hexfusion** [comment]
CI flaking :-1: 
/retest

**Comment by hexfusion** [comment]
cc @sdodson +1 4.4.6

**Comment by wking** [comment]
Still needs a `/lgtm` from someone on the etcd team, right?

**Comment by sdodson** [comment]
I'm no longer patch manager this week. Please just make sure that any PR you want to go in is waiting only on `cherry-pick-approved` and if it *must* go in this week that its severity is high or urgent and that it's obvious in the bug why it's higher than average severity.

**Comment by hexfusion** [comment]
cc @ashcrow

**Comment by ashcrow** [comment]
For whatever reason I don't have the ability to add labels to this repo. Checking other repos in the namespace I have the proper ability. Thank you @sdodson for manually adding the label :pray:.

**Pull request merged**
