### PR TITLE
NO-JIRA: replace nodelister with master nodelister

### PR DESCRIPTION
**Pull request by tjungblu**
From profiling on cert rotation we know that the node informer is called every couple of seconds on node heartbeats. This PR will ensure that all our node listers only ever listen/inform on the master node updates to reduce the frequency of unnecessary sync calls.

### CODE REVIEW

**Review by dusk125 — APPROVED** [review]
/lgtm

**Comment by tjungblu** [comment]
/hold cancel

@dusk125 could you take another look please? I've rebased to the merged changes in #1186

**Review by dusk125 — APPROVED** [review]
/lgtm

**Pull request merged**
