### PR TITLE
add env flags for different restore scenarios

### PR DESCRIPTION
**Pull request by tjungblu**
in order to do a simple restore from snapshot you can run this:

> [root@ci-ln-z11m7db-72292-s28sd-master-1 tmp]# export ETCD_RESTORE_SKIP_MOVE_CP_STATIC_PODS=true
> [root@ci-ln-z11m7db-72292-s28sd-master-1 tmp]# export ETCD_ETCDCTL_RESTORE=true
> [root@ci-ln-z11m7db-72292-s28sd-master-1 tmp]# ./cluster-restore.sh

### CODE REVIEW

**Comment by hasbro17** [comment]
Restore has nothing to do with scaling test

/override ci/prow/e2e-aws-ovn-etcd-scaling

Lgtm but needs `make update-bindata` (or `make update-generated` I forget which) to regenerate the bindata manifests

**Comment by tjungblu** [comment]
> Lgtm but needs make update-bindata (or make update-generated I forget which) to regenerate the bindata manifests

done. `make update` is enough btw :)

**Comment by Elbehery** [comment]
gr88 addition 👍🏽 

/lgtm
/approve

**Comment by tjungblu** [comment]
/hold cancel

waiting for the branch to open up again

**Comment by tjungblu** [comment]
AFAIU the feature branch is open again, since the bot doesn't want to update the label automatically:

/label jira/valid-bug

**Pull request closed without merging**
