### PR TITLE
Bug 2082312: Adding Thomas to reviewers, adding Allen to approvers

### PR DESCRIPTION
**Pull request by dusk125**
Backport of #815
https://bugzilla.redhat.com/show_bug.cgi?id=2082312

### CODE REVIEW

**Review by geliu2016 — APPROVED** [review]
/lgtm
/label cherry-pick-approved

**Comment by hasbro17** [comment]
/override ci/prow/e2e-operator
/override ci/prow/e2e-aws-single-node

No code change here.

**Comment by hasbro17** [comment]
@dusk125 We can backport this to 4.9 as well once it goes through. Or just use the cherry-pick cmd if you haven't cloned the BZ already.

**Pull request merged**
