### PR TITLE
Bug 2085997: removes TestScalingUpAndDownSingleNode

### PR DESCRIPTION
**Pull request by p0lyn0mial**
the test was moved to openshift/origin repo and is run as a part of openshift/conformance/serial suite

xref: https://github.com/openshift/origin/pull/26917

### CODE REVIEW

**Comment by p0lyn0mial** [comment]
/hold

until https://github.com/openshift/origin/pull/26917 merges

**Comment by p0lyn0mial** [comment]
failing `unit` fixed in https://github.com/openshift/cluster-etcd-operator/pull/814

**Review by geliu2016 — APPROVED** [review]
/lgtm

**Comment by p0lyn0mial** [comment]
I will keep it a few more days. I want to make sure the test in the origin repo won't get reverted. After that, I will merge this PR.

**Pull request merged**
