### PR TITLE
bug 1872802: remove old MCO etcd quorum guard resources

### PR DESCRIPTION
**Pull request by deads2k**
This cleans up the old mco pdb after the new one is in place.  It may fight with and old MCO operator, but only until that operator gets its new deployment.

### CODE REVIEW

**Comment by hexfusion** [comment]
/lgtm

cc @cgwalters @kikisdeliveryservice we feel that my changes in #1933 exposed a failure case that is blocking CI promotion.

**Comment by kikisdeliveryservice** [comment]
> /lgtm
> 
> cc @cgwalters @kikisdeliveryservice we feel that my changes in mco#1933 exposed a failure case that is blocking CI promotion.
@hexfusion 
Would you prefer to go with this PR _instead_ of the MCO PR or are we doing both?

**Comment by hexfusion** [comment]
> > /lgtm
> > cc @cgwalters @kikisdeliveryservice we feel that my changes in mco#1933 exposed a failure case that is blocking CI promotion.
> 
> @hexfusion
> Would you prefer to go with this PR _instead_ of the MCO PR or are we doing both?

this is just about to merge I am testing upgrade in clusterbot as well. I am going to raise a partial revert on #1933 in case.

**Comment by hexfusion** [comment]
bootstrap was a success MCD was happy[1], AWS test failures were related to Prometheus[2]

[1] https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_cluster-etcd-operator/429/pull-ci-openshift-cluster-etcd-operator-master-e2e-aws/1298691217453748224/artifacts/e2e-aws/gather-extra/pods/openshift-machine-config-operator_machine-config-daemon-5jpvp_machine-config-daemon.log

[2] https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-etcd-operator/429/pull-ci-openshift-cluster-etcd-operator-master-e2e-aws/1298691217453748224

**Comment by hexfusion** [comment]
```
test upgrade quay.io/openshift-release-dev/ocp-release:4.5.7-x86_64 registry.svc.ci.openshift.org/ci-op-hhyj4fic/release:latest 
```
Clusterbot upgrade was a success.

https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-origin-installer-launch-gcp/1298724636363591680

**Pull request merged**
