### PR TITLE
Bug 1840150: operator: add fsync controller

### PR DESCRIPTION
**Pull request by retroflexer**
This is a manual cherry pick of PR https://github.com/openshift/cluster-etcd-operator/pull/313 on the top of PR 365.

313: Add controller that watches leader changes and capture disk metrics

### CODE REVIEW

**Comment by retroflexer** [comment]
Hold until PR https://github.com/openshift/cluster-etcd-operator/pull/365  merges.

/hold

**Comment by retroflexer** [comment]
@hexfusion Do you understand why the test images failing here?

**Comment by hexfusion** [comment]
> @hexfusion Do you understand why the test images failing here, although, it passed once?
> 
> Passed here: https://deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-etcd-operator/369/pull-ci-openshift-cluster-etcd-operator-release-4.4-images/137

seems to be flakes

**Comment by hexfusion** [comment]
/hold 

@retroflexer feel free to unhold when you have upgrade test proof

**Comment by retroflexer** [comment]
The upgrade from 4.3 to this PR is tested to working successfully:

cluster-bot: job test upgrade 4.3 openshift/cluster-etcd-operator#369 succeeded
Logs: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-launch-aws/13157

**Pull request merged**
