### PR TITLE
Revert "ETCD-579: store revision at which signers are rotated"

### PR DESCRIPTION
**Pull request by tjungblu**
Reverts openshift/cluster-etcd-operator#1235

### CODE REVIEW

**Comment by derekhiggins** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.16-e2e-metal-ipi-ovn-ipv6

**Comment by tjungblu** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.16-e2e-metal-ipi-ovn-ipv6

**Comment by hasbro17** [comment]
Unrelated OLM failure in the fips job and that qe job hasn't passed in recent memory.

/override ci/prow/e2e-operator-fips

**Pull request merged**
