### PR TITLE
OCPBUGS-7510: [release-4.11] fail early on missing node status envs

### PR DESCRIPTION
**Pull request by tjungblu**
cherry-pick from #1004 and manual go mod tidy

### CODE REVIEW

**Review by geliu2016 — APPROVED** [review]
/lgtm

**Comment by tjungblu** [comment]
@geliu2016 I think that CPA command did not go through :/

**Comment by Elbehery** [comment]
> @geliu2016 I think that CPA command did not go through :/

Yes, @mfojtik or @deads2k can do though 

Also I think @geliu2016 should be added to `patch-manager` list 🤔

**Pull request merged**
