### PR TITLE
Bug 1846574: bindata/bootkube/bootstrap-manifests: add proper env to metrics container on bootstrap.

### PR DESCRIPTION
**Pull request by hexfusion**
Signed-off-by: Sam Batschelet <sbatsche@redhat.com>

### CODE REVIEW

**Comment by ironcladlou** [comment]
What job will verify this?

**Comment by hexfusion** [comment]
> What job will verify this?

none

**Comment by hexfusion** [comment]
@ironcladlou we should consider another action item from this.

As monitoring does not actually harvest bootstrap etcd metrics.

- should/can it?
- depending on above should we just save resources and remove the container altogether.

**Comment by hexfusion** [comment]
This PR is no longer necessary as we removed the metrics container from bootstrap all together in https://github.com/openshift/cluster-etcd-operator/pull/416

**Pull request closed without merging**
