### PR TITLE
TRT-1485: Revert #1177 "ETCD-512: refactoring the cert signer controller"

### PR DESCRIPTION
**Pull request by dgoodwin**
Reverts #1177 ; tracked by [TRT-1485](https://issues.redhat.com//browse/TRT-1485)

Per [OpenShift policy](https://github.com/openshift/enhancements/blob/master/enhancements/release/improving-ci-signal.md#quick-revert), we are reverting this breaking change to get CI and/or nightly payloads flowing again.

TRT tooling picked up an alert firing we've never seen yet in 4.16, in 30-40% of minor upgrades (micro may not be affected) called  PrometheusOperatorRejectedResources, which monitoring team helped us trace back to an error getting the etcd-metric-client secret. This alert fired for about 23 minutes and then resolved.

To unrevert this, revert this PR, and layer an additional separate commit on top that addresses the problem. Before merging the unrevert, please run these jobs on the PR and check the result of these jobs to confirm the fix has corrected the problem:

```
/payload-aggregate periodic-ci-openshift-release-master-ci-4.16-upgrade-from-stable-4.15-e2e-aws-ovn-upgrade
```

CC: @tjungblu

<div align="right">
PR created by <a href="https://github.com/stbenjam/revertomatic">Revertomatic<sup>:tm:</sup></a>
</div>

### CODE REVIEW

**Comment by tjungblu** [comment]
would've been too easy :)

Thanks for digging this up @simonpasquier 

/lgtm

**Comment by dgoodwin** [comment]
Wow you saw that fast. :muscle:  Thanks @tjungblu !

**Comment by tjungblu** [comment]
We were internally waiting for this to happen because it's quite a big change. We ran the blocking payloads over 50 times, but we only caught it once or twice thinking it was some prom flakiness.

**Comment by tjungblu** [comment]
fix in #1194

**Pull request merged**
