### PR TITLE
Bug 1999777: [release-4.8]: pkg/operator: add cluster backup upgrade controller

### PR DESCRIPTION
**Pull request by hexfusion**
Manual cherry-pick of #647 and #653

Signed-off-by: Sam Batschelet <sbatsche@redhat.com>

/hold

### CODE REVIEW

**Review by lilic — COMMENTED** [review]
/lgtm

The test skip did not work FYI.

**Comment by hexfusion** [comment]
/override ci/prow/e2e-gcp-upgrade-five-control-plane-replicas

**Comment by lilic** [comment]
Yay optional five-conrol-plane works 🎉 :) 

/retest

For single node.

**Review by lilic — APPROVED** [review]
/lgtm

**Comment by mfojtik** [comment]
[patch-manager] :rocket: Approved for z-stream by score: 0.50

adding cherry-pick approved

**Pull request merged**
