### PR TITLE
OCPBUGS-2577: fix cert rotation on IP changes

### PR DESCRIPTION
**Pull request by tjungblu**
pick and fix of https://github.com/openshift/cluster-etcd-operator/pull/945

plus adding goland to gitignore as separate commit

### CODE REVIEW

**Comment by tjungblu** [comment]
@geliu2016 fyi when you find some time, that's the last of the chain. Thanks for testing this all the way down so far :)

**Review by geliu2016 — APPROVED** [review]
/label cherry-pick-approved

**Pull request merged**
