### PR TITLE
WIP pkg/operator/hostetcdendpointcontroller: disable host-etcd update duing cluster bootstrap

### PR DESCRIPTION
**Pull request by hexfusion**
Depends on https://github.com/openshift/installer/pull/2998

Signed-off-by: Sam Batschelet <sbatsche@redhat.com>

### CODE REVIEW

**Comment by hexfusion** [comment]
Since we are in a bit of a chicken and egg scenario I think the only path forward is to go `Unmanaged` merge the installer PR then go back to `Managed` and merge this PR.

**Comment by hexfusion** [comment]
# retest for cycles

/test e2e-azure

**Comment by hexfusion** [comment]
flake

/test e2e-gcp-upgrade

**Comment by deads2k** [comment]
superceded in master

**Pull request closed without merging**
