### PR TITLE
Bug 1825236: Fix podman auth

### PR DESCRIPTION
**Pull request by retroflexer**
This is a manual cherry pick of PR: https://github.com/openshift/cluster-etcd-operator/pull/320.

### CODE REVIEW

**Comment by hexfusion** [comment]
@retroflexer why pick the typo?

**Comment by retroflexer** [comment]
> @retroflexer why pick the typo?

Well, for not breaking the commit chain :-).

**Comment by retroflexer** [comment]
> @retroflexer why pick the typo?

Deleted the other commit, and reworded the single commit.

**Pull request merged**
