### PR TITLE
test-wise etcd verbose

### PR DESCRIPTION
**Pull request by tjungblu**
/hold

### CODE REVIEW

**Comment by xueqzhan** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.14-e2e-azure-ovn-upgrade

**Comment by xueqzhan** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.14-upgrade-from-stable-4.13-e2e-azure-sdn-upgrade

**Comment by xueqzhan** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.13-upgrade-from-stable-4.12-e2e-azure-sdn-upgrade

**Comment by xueqzhan** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.13-upgrade-from-stable-4.12-e2e-azure-sdn-upgrade

**Comment by xueqzhan** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.13-upgrade-from-stable-4.12-e2e-azure-sdn-upgrade

**Comment by tjungblu** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.13-upgrade-from-stable-4.12-e2e-azure-sdn-upgrade

**Pull request closed without merging**
