### PR TITLE
OCPBUGS-19052: Avoid caching etcdctl on cluster-backup.sh

### PR DESCRIPTION
**Pull request by tjungblu**

### CODE REVIEW

**Comment by tjungblu** [comment]
/hold

something's off with the backups

**Comment by tjungblu** [comment]
hmm, works when running locally against clusterbot...

/retest

**Comment by tjungblu** [comment]
okay that's getting very strange :rofl: 

```
+ /usr/local/bin/cluster-backup.sh --force /etc/kubernetes/cluster-backup/backup-backup-happy-path-2023-09-15_131102
found latest kube-apiserver: /etc/kubernetes/static-pod-resources/kube-apiserver-pod-6
found latest kube-controller-manager: /etc/kubernetes/static-pod-resources/kube-controller-manager-pod-7
found latest kube-scheduler: /etc/kubernetes/static-pod-resources/kube-scheduler-pod-6
found latest etcd: /etc/kubernetes/static-pod-resources/etcd-pod-8
/etc/kubernetes/static-pod-resources/etcd-certs/configmaps/etcd-scripts/etcd-common-tools: line 18: podman: command not found
/etc/kubernetes/static-pod-resources/etcd-certs/configmaps/etcd-scripts/etcd-common-tools: line 19: podman: command not found
umount: : no mount point specified.
```

**Review by geliu2016 — APPROVED** [review]
/label cherry-pick-approved

**Comment by tjungblu** [comment]
The backups we test run on the etcd container image, so they have no podman, yet etcdctl. I've accomodated this in the backup script now - let's see if it passes :)

**Comment by tjungblu** [comment]
/hold 
waiting for the e2e operator tests to pass

**Comment by tjungblu** [comment]
/hold cancel

good to go! :tada:

**Pull request merged**
