### PR TITLE
Bug 1883689: Add validation for logLevel

### PR DESCRIPTION
**Pull request by dmage**
openshift/api#736 added restrictions for logLevel values. This PR vendors new openshift/api to get new CRDs. Also it replaces manifests/0000_12_etcd-operator_01_config.crd.yaml with yaml from openshift/api.

### CODE REVIEW

**Comment by hexfusion** [comment]
/hold
for https://github.com/openshift/api/pull/752

**Comment by dmage** [comment]
/retitle Bug 1883689: Add validation for logLevel

**Pull request merged**
