### PR TITLE
 [release-4.11] Bug 2108595: Cherrypick remove etcd dashboards from Hypershift

### PR DESCRIPTION
**Pull request by Elbehery**
This PR is a manual cherry pick from https://github.com/openshift/cluster-etcd-operator/pull/897

### CODE REVIEW

**Comment by tjungblu** [comment]
@geliu2016 can you take a look once you find some time? :)

**Comment by alvaroaleman** [comment]
This currently breaks hypershift on 4.12. The backport here must include the change in https://github.com/openshift/cluster-etcd-operator/pull/917, otherwise it will break 4.11 hypershift

**Comment by Elbehery** [comment]
Thanks @alvaroaleman  👍🏽  .. I have cherrypicked your commit atop my branch .. 

Appreciate it 🙏🏽

**Review by geliu2016 — APPROVED** [review]
/lgtm

**Review by geliu2016 — APPROVED** [review]
/lgtm

**Comment by Elbehery** [comment]
@geliu2016  hello ✋🏽  , this needs `cherry-pick-approved label.`

**Comment by Elbehery** [comment]
@hasbro17  hello ✋🏽 , this needs cherry-pick-approved label.

**Pull request merged**
