### PR TITLE
WIP: OCPBUGS-17199: skip stability check on the nodes, if the machine hosting the node is in deleting status

### PR DESCRIPTION
**Pull request by jubittajohn**
Dependant on PR: https://github.com/openshift/library-go/pull/1799

### CODE REVIEW

**Comment by tjungblu** [comment]
^ those are usually the test that would break on this change

**Comment by hasbro17** [comment]
/test e2e-metal-assisted
/test e2e-metal-ipi-ovn-ipv6

Don't see those running.

**Pull request closed without merging**
