### PR TITLE
Bug 1840150: operator: add fsync controller

### PR DESCRIPTION
**Pull request by retroflexer**
Manual cherry pick of PR https://github.com/openshift/cluster-etcd-operator/pull/313

### CODE REVIEW

**Comment by hexfusion** [comment]
@retroflexer I think we are missing some of the vendor updates,try.

go mod tidy;go mod vendor

I think we have a makefile invocation that handles this as well.

**Comment by retroflexer** [comment]
> @retroflexer I think we are missing some of the vendor updates,try.
> 
> go mod tidy;go mod vendor
> 
> I think we have a makefile invocation that handles this as well.
I think we need to port all the changes for PR 311 (https://github.com/openshift/cluster-etcd-operator/pull/311). I will do it in that order.

**Comment by hexfusion** [comment]
> > @retroflexer I think we are missing some of the vendor updates,try.
> > go mod tidy;go mod vendor
> > I think we have a makefile invocation that handles this as well.
> 
> I think we need to port all the changes for PR 311 (#311). I will do it in that order.

OK, so you will do that in another PR?

**Comment by retroflexer** [comment]
> OK, so you will do that in another PR?

I am getting there. Sorry the tree shaking is taking a while for me.

**Comment by retroflexer** [comment]
> OK, so you will do that in another PR?
Here is the PR as a combined cherrypick of 311 and 270:
https://github.com/openshift/cluster-etcd-operator/pull/365

I will push PR 362 once 365 gets merged.

**Comment by retroflexer** [comment]
Hold until PR 365 (https://github.com/openshift/cluster-etcd-operator/pull/365) merges.

/hold

**Comment by retroflexer** [comment]
Superseded by https://github.com/openshift/cluster-etcd-operator/pull/369.

/close

**Pull request closed without merging**
