### PR TITLE
NO-JIRA: degrade targetconfigcontroller on quorum loss

### PR DESCRIPTION
**Pull request by tjungblu**
This is a more general refactoring to degrade the whole controller when quorum is lost. This should make it easier to assert in e2e tests and is more consistent with the behavior in the other controllers.

### CODE REVIEW

**Comment by tjungblu** [comment]
unrelated failure in kube version migration 

/override ci/prow/e2e-aws-ovn-etcd-scaling

**Comment by hasbro17** [comment]
/override ci/prow/e2e-aws-ovn-etcd-scaling

Scaling test has already passed in that run
https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_cluster-etcd-operator/1309/pull-ci-openshift-cluster-etcd-operator-master-e2e-aws-ovn-etcd-scaling/1818957024638013440

**Comment by hasbro17** [comment]
> tjungblu unauthorized: /override is restricted to Repo administrators, approvers in top level OWNERS file

But we're all approvers in the OWNERS file so what gives?
https://github.com/openshift/cluster-etcd-operator/blob/master/OWNERS

**Comment by tjungblu** [comment]
I've opened a DPTP bug already:
https://issues.redhat.com/browse/DPTP-4116

**Pull request merged**
