### PR TITLE
OCPBUGS-42083: go back to HA mode in bootstrap

### PR DESCRIPTION
**Pull request by tjungblu**
This reverts the quorum guard back to ensure we can't violate the quorum during bootstrap time.

We still keep this behavior in DelayedScaling, which is used by ass. installer.

### CODE REVIEW

**Comment by tjungblu** [comment]
/payload-aggregate periodic-ci-openshift-release-master-ci-4.17-e2e-azure-ovn-upgrade 10

**Comment by tjungblu** [comment]
/payload-aggregate periodic-ci-openshift-release-master-ci-4.17-e2e-azure-ovn-upgrade 10

**Comment by tjungblu** [comment]
/payload-aggregate periodic-ci-openshift-release-master-ci-4.17-e2e-azure-ovn-upgrade 10

**Comment by tjungblu** [comment]
/payload-aggregate periodic-ci-openshift-release-master-ci-4.17-e2e-azure-ovn-upgrade 10

**Comment by hasbro17** [comment]
/lgtm

I'm guessing this will slow down the bootstrap scale up time. We should probably keep an eye on this in case this trips up any other tests that may be affected by that.

/hold

To verify the aggregate upgrade runs. Unhold whenever that seems good.

**Comment by tjungblu** [comment]
/payload-aggregate periodic-ci-openshift-release-master-ci-4.17-e2e-azure-ovn-upgrade 10

**Comment by tjungblu** [comment]
/close

seems we don't need this for the time being

**Pull request closed without merging**
