### PR TITLE
Bug 2089199: Move etcd monitoring dashboards CEO

### PR DESCRIPTION
**Pull request by Elbehery**
This PR migrates etcd grafana dashboard to CEO

cc @simonpasquier

### CODE REVIEW

**Comment by simonpasquier** [comment]
IIUC the jsonnet workflow is to bump the jsonnet dependencies and call [hack/generate.sh](https://github.com/openshift/cluster-etcd-operator/blob/master/hack/generate.sh) to update the generated files in manifests/.

You could modify the script to have it generate the dashboard configmap from the mixin code:

```
...
cd jsonnet && jb update
jsonnet -J vendor main.jsonnet  | gojsontoyaml > ../manifests/0000_90_etcd-operator_03_prometheusrule.yaml
jsonnet -J vendor dashboard.jsonnet  | gojsontoyaml > ../manifests/0000_90_cluster-etcd-operator_01-dashboards.yaml
```

dashboard.jsonnet could look like

```
local etcdMixin = (import 'github.com/etcd-io/etcd/contrib/mixin/mixin.libsonnet');

{
  apiVersion: 'v1',
  kind: 'ConfigMap',
  metadata: {
    annotations: {
      'include.release.openshift.io/ibm-cloud-managed': 'true',
      'include.release.openshift.io/self-managed-high-availability': 'true',
      'include.release.openshift.io/single-node-developer': 'true',
    },
    labels: {
      'console.openshift.io/dashboard': 'true',
    },
    name: 'etcd-dashboard',
    namespace: 'openshift-config-managed',
  },
  data: {
    'etcd.json': std.manifestJsonEx(etcdMixin.grafanaDashboards['etcd.json'], '    '),
  },
}
```

**Comment by Elbehery** [comment]
@simonpasquier thanks a lot for your comment, I have updated the PR accordingly

**Comment by simonpasquier** [comment]
/lgtm
I'd recommend that you put this on hold until https://github.com/openshift/cluster-monitoring-operator/pull/1674 is in good shape. Then wa can verify with cluster-bot that the 2 PRs work together as expected.

**Comment by Elbehery** [comment]
> /lgtm I'd recommend that you put this on hold until [openshift/cluster-monitoring-operator#1674](https://github.com/openshift/cluster-monitoring-operator/pull/1674) is in good shape. Then wa can verify with cluster-bot that the 2 PRs work together as expected.

will do now, thanks so much for the review and help 🙏🏽

**Comment by tjungblu** [comment]
awesome addition! 

/lgtm
/test e2e-agnostic

**Comment by tjungblu** [comment]
@Elbehery sorry for the conflict, could you run `hack/generate.sh` after rebasing this against master?

**Review by geliu2016 — APPROVED** [review]
/lgtm 
/label cherry-pick-approved

**Comment by Elbehery** [comment]
@JoaoBraveCoding  @simonpasquier  Have you merged https://github.com/openshift/cluster-monitoring-operator/pull/1674 ?

**Pull request merged**
