### PR TITLE
OCPBUGS-13547: Remove featureset flag and use only the manifest

### PR DESCRIPTION
**Pull request by deads2k**
The manifest now exists in every install and can be used by bootstrapping. The installer passes the arg now, so we can update the operator to only honor the manifest and eliminate interpretation.

peer to https://github.com/openshift/cluster-kube-apiserver-operator/pull/1491

This also updates to the latest kube.

### CODE REVIEW

**Comment by tjungblu** [comment]
@deads2k build complains about `note: module requires Go 1.20`

**Comment by deads2k** [comment]
> @deads2k build complains about `note: module requires Go 1.20`

yeah, I expected to see an ART PR here to merge.

**Comment by tjungblu** [comment]
@deads2k feel free to hit the merge button on https://github.com/openshift/cluster-etcd-operator/pull/1047

**Comment by hasbro17** [comment]
Scaling test is good, just a disruption test that it's flaking on:
```
kube-api-reused-connections was unreachable during disruption testing for at least 1s of 32m25s (maxAllowed=0s):
```
/override ci/prow/e2e-aws-ovn-etcd-scaling

/lgtm

**Comment by deads2k** [comment]
cleaning up the remnants for external cloud provider

**Pull request merged**
