### PR TITLE
[Bug 1807493]: Add recovery scripts to ceo

### PR DESCRIPTION
**Pull request by retroflexer**
Added the recovery scripts needed for Disaster Recovery in 4.4:
etcd-restore-backup.sh
etcd-snapshot-backup.sh
etcd-member-remove.sh
openshift-recovery-tools

### CODE REVIEW

**Comment by deads2k** [comment]
need to run `make update-bindata`

**Comment by retroflexer** [comment]
> need to run `make update-bindata`

@deads2k checked in immediately 
(https://github.com/openshift/cluster-etcd-operator/pull/212#event-3075131631)

**Comment by deads2k** [comment]
we can start here.

/lgtm

**Pull request merged**
