### PR TITLE
Bug 1809732: cluster-etcd-operator: upgrades show "etcd member is unavailable"

### PR DESCRIPTION
**Pull request by sanchezl**

### CODE REVIEW

**Comment by deads2k** [comment]
@sanchezl for debugging?  If so, write a bug and get this merged.

**Comment by deads2k** [comment]
/hold

this will flap the kas-o configuration on consumption.  Logging good, flapping bad.

**Comment by sanchezl** [comment]
Superseded by https://github.com/openshift/cluster-etcd-operator/pull/229

**Pull request closed without merging**
