### PR TITLE
ETCD-359: Remove quorum guard cleanup controller

### PR DESCRIPTION
**Pull request by Elbehery**
fixes https://issues.redhat.com/browse/ETCD-359

### CODE REVIEW

**Comment by tjungblu** [comment]
/lgtm

one less moving part :)

**Comment by Elbehery** [comment]
@hasbro17  hello ✋🏽  .. can you override here as well please ?

**Comment by hasbro17** [comment]
@Elbehery  Also please remove the stale conditions remover. That was needed for 4.10->4.11 to remove the leftover operator status condition from the quorumguard controller in 4.10 as you upgraded to 4.11. We shouldn't need that anymore.

https://github.com/openshift/cluster-etcd-operator/blob/52cb67e0a9937b00d5dc12e04a37b54fba9fcda4/pkg/operator/starter.go#L404-L412

https://github.com/openshift/cluster-etcd-operator/blob/52cb67e0a9937b00d5dc12e04a37b54fba9fcda4/pkg/operator/starter.go#L421

**Comment by Elbehery** [comment]
> @Elbehery Also please remove the stale conditions remover. That was needed for 4.10->4.11 to remove the leftover operator status condition from the quorumguard controller in 4.10 as you upgraded to 4.11. We shouldn't need that anymore.
> 
> https://github.com/openshift/cluster-etcd-operator/blob/52cb67e0a9937b00d5dc12e04a37b54fba9fcda4/pkg/operator/starter.go#L404-L412
> 
> https://github.com/openshift/cluster-etcd-operator/blob/52cb67e0a9937b00d5dc12e04a37b54fba9fcda4/pkg/operator/starter.go#L421

done 👍🏽

**Comment by hasbro17** [comment]
You need to update the deps.
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-etcd-operator/980/pull-ci-openshift-cluster-etcd-operator-master-verify-deps/1613279780105359360

**Comment by Elbehery** [comment]
> You need to update the deps. https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-etcd-operator/980/pull-ci-openshift-cluster-etcd-operator-master-verify-deps/1613279780105359360

i ran `make verify` locally before pushing !!! 

will fix it now, thx a lot 👍🏽

**Comment by Elbehery** [comment]
> You need to update the deps. https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-etcd-operator/980/pull-ci-openshift-cluster-etcd-operator-master-verify-deps/1613279780105359360

fixed 👍🏽 

Do we need cherry-pick for this as well ?

**Pull request merged**
