### PR TITLE
[release-4.9] OCPBUGS-7982: fail early on missing node status envs

### PR DESCRIPTION
**Pull request by tjungblu**

### CODE REVIEW

**Comment by tjungblu** [comment]
/retitle [release-4.9] OCPBUGS-7982: fail early on missing node status envs #1015

**Comment by tjungblu** [comment]
/retitle [release-4.9] OCPBUGS-7982: fail early on missing node status envs

**Review by geliu2016 — APPROVED** [review]
/label cherry-pick-approved

**Pull request merged**
