### PR TITLE
manifests: bump loglevel of operator to normal

### PR DESCRIPTION
**Pull request by lance5890**
[issue 1061](https://github.com/openshift/cluster-etcd-operator/issues/1061)

### CODE REVIEW

**Comment by lance5890** [comment]
related to https://github.com/openshift/cluster-kube-scheduler-operator/pull/487

**Comment by tjungblu** [comment]
Thanks @lance5890, I don't quite think this makes sense but there's no sense in blocking any further ;)

**Comment by lance5890** [comment]
> Thanks @lance5890, I don't quite think this makes sense but there's no sense in blocking any further ;)

it can be treated as kind of cleanup

**Comment by tjungblu** [comment]
unrelated failure

/override ci/prow/e2e-aws-ovn-serial

/lgtm

**Pull request merged**
