### PR TITLE
OCPBUGS-3929: update apf configuration to use v1beta2

### PR DESCRIPTION
**Pull request by tkashem**

### CODE REVIEW

**Comment by tkashem** [comment]
/hold
we need to wait for 1.26 kube bump pr to merge first

**Review by soltysh — APPROVED** [review]
/lgtm

**Comment by hasbro17** [comment]
Looks like an infra failure now:
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-etcd-operator/966/pull-ci-openshift-cluster-etcd-operator-master-e2e-aws-ovn-single-node/1595112758515339264#1:build-log.txt%3A79-94
```
level=error msg=Error: error reading Route in Route Table (rtb-0061dcf3bf949cc64) with destination (0.0.0.0/0): couldn't find resource
level=error
level=error msg=  with module.vpc.aws_route.igw_route[0],
level=error msg=  on vpc/vpc-public.tf line 34, in resource "aws_route" "igw_route":
level=error msg=  34: resource "aws_route" "igw_route" {
level=error
level=error msg=failed to fetch Cluster: failed to generate asset "Cluster": failure applying terraform for "cluster" stage: failed to create cluster: failed to apply Terraform: exit status 1
level=error
level=error msg=Error: error reading Route in Route Table (rtb-0061dcf3bf949cc64) with destination (0.0.0.0/0): couldn't find resource
level=error
level=error msg=  with module.vpc.aws_route.igw_route[0],
level=error msg=  on vpc/vpc-public.tf line 34, in resource "aws_route" "igw_route":
level=error msg=  34: resource "aws_route" "igw_route" {
```
Seeing it all across CI so likely unrelated:
https://search.ci.openshift.org/?search=error+reading+Route+in+Route+Table&maxAge=48h&context=1&type=bug%2Bissue%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job

I'll try again in a bit and if it doesn't resolve we can override.

**Comment by tjungblu** [comment]
@hasbro17 while you're at it doing the overrides, there's two other PRs being stuck on this too:

https://github.com/openshift/cluster-etcd-operator/pull/935
https://github.com/openshift/cluster-etcd-operator/pull/964

**Pull request merged**
