### PR TITLE
NO-JIRA: remove cluster-backup pod

### PR DESCRIPTION
**Pull request by lance5890**
As the UpgradeBackupController has been removed by the PR https://github.com/openshift/cluster-etcd-operator/pull/1129

the cluster-backup-pod has no effect anymore

### CODE REVIEW

**Comment by lance5890** [comment]
This test is being made optional https://github.com/openshift/release/pull/47252

**Comment by tjungblu** [comment]
Thanks @lance5890! We have to wait until the nightly builds are catching up and the label requirements are lifted, but otherwise 

/lgtm

**Comment by tjungblu** [comment]
@lance5890 it will likely retest for a while, I'll keep an eye out to get this merged soonish

**Comment by tjungblu** [comment]
/override ci/prow/e2e-agnostic-ovn-upgrade
/override ci/prow/e2e-gcp-qe-no-capabilities
/override ci/prow/e2e-aws-ovn-single-node


unrelated failures

**Comment by tjungblu** [comment]
Thanks @lance5890 and sorry for the long wait

**Pull request merged**
