### PR TITLE
turn on initial corruption check

### PR DESCRIPTION
**Pull request by deads2k**
Something to talk about.  I don't fully understand what https://github.com/etcd-io/etcd/blob/main/server/etcdserver/corrupt.go#L39-L121 does yet.

/hold

holding until I understand the impacts and risks.

### CODE REVIEW

**Comment by Elbehery** [comment]
> Something to talk about. I don't fully understand what https://github.com/etcd-io/etcd/blob/main/server/etcdserver/corrupt.go#L39-L121 does yet.

@deads2k  it does compare the hash of the peers with the hash of its data and based on this decides if there is data inconsistency

**Comment by deads2k** [comment]
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-etcd-operator/770/pull-ci-openshift-cluster-etcd-operator-master-e2e-aws-single-node/1508365324532060160  failed on the too many watches for node-tuning which is currently pervasive.

/override ci/prow/e2e-aws-single-node

**Comment by mfojtik** [comment]
the e2e-operator failed on AWS quota, unrelated

**Comment by mfojtik** [comment]
/override ci/prow/e2e-operator

we had a green run, since then the job failing on AWS infrastructure issues, not related to etcd or this change.

**Comment by sdodson** [comment]
/retitle Bug 2068601: turn on initial corruption check

**Pull request merged**
