### PR TITLE
bug 1798219: use dynamic client instead of taking an MCO dependency

### PR DESCRIPTION
**Pull request by deads2k**
mco prevents go mod from working and this removes the one dep

### CODE REVIEW

**Comment by mfojtik** [comment]
LGTM

**Comment by hexfusion** [comment]
Nice to drop the dep here thanks @deads2k 

/lgtm

**Comment by hexfusion** [comment]
cc @alaypatel07

**Comment by abhinavdahiya** [comment]
/cc @runcom 

because he might get stuck supporting something when they change for igntion 3.

**Pull request merged**
