### PR TITLE
Bug 2053596: Increase IBMCloud VPC heartbeat timeout to 500ms and leader election timeout to 2500ms

### PR DESCRIPTION
**Pull request by dusk125**
Work in progress fix for: https://bugzilla.redhat.com/show_bug.cgi?id=2055833

### CODE REVIEW

**Comment by rvanderp3** [comment]
In case it is helpful here, https://github.com/openshift/release/pull/26803 has been created to enable testing of the e2e-ibmcloud workflow.

**Comment by cjschaef** [comment]
Testing the above changes after cherry-picking to 4.10 I get the following errors when the bootstrap node pods are trying to come up
```
Mar 08 20:59:11 cjs-test-23-ct25v-bootstrap bootkube.sh[2381]: etcdctl failed. Retrying in 5 seconds...
Mar 08 20:59:21 cjs-test-23-ct25v-bootstrap bootkube.sh[2381]: {"level":"warn","ts":1646773161.9213018,"logger":"client","caller":"v3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc00031aa80/#initially=[https://localhost:2379]","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = \"transport: Error while dialing dial tcp [::1]:2379: connect: connection refused\""}
Mar 08 20:59:21 cjs-test-23-ct25v-bootstrap bootkube.sh[2381]: https://localhost:2379 is unhealthy: failed to commit proposal: context deadline exceeded
Mar 08 20:59:21 cjs-test-23-ct25v-bootstrap bootkube.sh[2381]: Error: unhealthy cluster
Mar 08 20:59:22 cjs-test-23-ct25v-bootstrap bootkube.sh[2381]: etcdctl failed. Retrying in 5 seconds...
```

Also, there is a bug currently in the `installer` that does not set the `providerType`, which I believe is also going to affect this, not taking into account the changes this code intends to set.
https://github.com/openshift/installer/pull/5687

My testing above was done with the `installer` fix, just FYI, which appears to work normally with the current 4.10 code level

**Comment by cjschaef** [comment]
I've been doing extensive testing on using these values (500ms/2500ms), compared with bumping it further to 2sec/10sec, and it does appear to alleviate some issues with etcd. This fix may not be sufficient in the long run, but potential etcd configuration during IPI, and IBM Cloud VPC IOPS for boot volumes feature are likely required to help solve the issue long term.

I think these results are sufficient for now, until a deep investigation could provide better tweaking. This PR should at least fix the bug where previous configuration for IBM Cloud was not making it into the cluster (only at a bootstrap etcd level).

**Comment by dusk125** [comment]
/retitle Bug 2053596: Increase IBMCloud VPC heartbeat timeout to 500ms and leader election timeout to 2500ms

**Review by geliu2016 — APPROVED** [review]
/lgtm

**Pull request merged**
