### PR TITLE
Bug 2075015: Revert "replace quorumguard and add readyz server"

### PR DESCRIPTION
**Pull request by dgoodwin**
Reverts openshift/cluster-etcd-operator#763

We suspect this has caused a payload blocking regression. Opening revert to prove.

https://bugzilla.redhat.com/show_bug.cgi?id=2075015

### CODE REVIEW

**Comment by dgoodwin** [comment]
Still waiting on Azure but AWS cleared, I think this proves the revert works.

**Comment by hasbro17** [comment]
Going to override so we can fix payload promotion sooner:
/override ci/prow/e2e-operator 
/override ci/prow/e2e-aws-single-node
/override ci/prow/e2e-agnostic-upgrade
/skip ci/prow/e2e-gcp-five-control-plane-replicas

**Pull request merged**
