### PR TITLE
Bug 1831664: [release-4.4]: pkg/cmd/render: Backport adding support for s390 and s390x arch

### PR DESCRIPTION
**Pull request by Prashanth684**
This is a backport of #317 with a few minor changes that were needed for 4.4

### CODE REVIEW

**Comment by retroflexer** [comment]
This manual cherrypick will break the commit chain. We are preparing 4.5 commits needed for 4.4.z release this Friday, and will certainly include all the PRs needed for this PR to be merged into 4.4 in a clean manner. 

/hold

**Comment by hexfusion** [comment]
https://github.com/openshift/cluster-etcd-operator/pull/316 should land first

**Comment by hexfusion** [comment]
@sdodson I am transferring cherry-pick-approved to #348 which supersedes this.

**Pull request closed without merging**
