### PR TITLE
Bug 1832919: Stop reconciling in response to global configmap events

### PR DESCRIPTION
**Pull request by retroflexer**
This is a manual cherry pick of https://github.com/openshift/cluster-etcd-operator/pull/332.

### CODE REVIEW

**Comment by retroflexer** [comment]
@ironcladlou here is the cherry pick of your change 332. Thanks for the great fix.

**Comment by ironcladlou** [comment]
Thanks!

/lgtm

**Comment by sdodson** [comment]
This is believed to be a significant contributor to the increased rate of etcd overload timeouts observed in upgraded and fresh install 4.4 clusters. Overriding valid-bug flag as QE hasn't had opportunity to test upstream yet.

**Comment by sdodson** [comment]
/override ci/prow/e2e-metal-ipi
This test has never passed.

**Pull request merged**
