### PR TITLE
Bug 1823608: fix message reporting for etcdmemberscontroller

### PR DESCRIPTION
**Pull request by retroflexer**
Cherry picking from PRs https://github.com/openshift/cluster-etcd-operator/pull/290 and https://github.com/openshift/cluster-etcd-operator/pull/318.

### CODE REVIEW

**Comment by retroflexer** [comment]
I added release 4.4 because it makes it clear to us when we are looking at the PR list, and I thought it doesn't hurt the process (although it is not mandatory anymore).

**Comment by hexfusion** [comment]
I was told that we don't want the branch because of the release notes getting gummed up. cc @wking

**Pull request merged**
