### PR TITLE
Bug 2063831: Replace quorumguard and add readyz server

### PR DESCRIPTION
**Pull request by hasbro17**
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2063831

This PR replaces the use of the etcd-operator's existing quorum guard controller with the staticpod controller's method of force assigning guard pods directly to the nodes. This should address the issue of two quorum guard pods erroneously landing on the same node.

Un-revert of https://github.com/openshift/cluster-etcd-operator/pull/787
Originally: https://github.com/openshift/cluster-etcd-operator/pull/763

Needs to address the following issue (https://bugzilla.redhat.com/show_bug.cgi?id=2075015) with `payload 4.11 nightly blocking` job on aws and azure for repeated events for the readiness probe failing to connect:
```
: [sig-arch] events should not repeat pathologically expand_less 	0s
{  1 events happened too frequently

event happened 65 times, something is wrong: ns/openshift-etcd pod/etcd-guard-ip-10-0-176-75.us-west-2.compute.internal node/ip-10-0-176-75.us-west-2.compute.internal - reason/ProbeError Readiness probe error: Get "https://10.0.176.75:9980/healthz": dial tcp 10.0.176.75:9980: connect: connection refused
body: 
}
```

### CODE REVIEW

**Comment by deads2k** [comment]
@hasbro17 update the test to flake-only and take it as a bug that needs to be fixed like a peer to the current PDB failures.

**Comment by hasbro17** [comment]
/retitle Bug 2063831: Replace quorumguard and add readyz server

**Comment by hasbro17** [comment]
/payload 4.11 nightly blocking

Now that https://github.com/openshift/origin/pull/27016 is merged

**Comment by deads2k** [comment]
aggregation in https://pr-payload-tests.ci.openshift.org/runs/ci/b8dd2e30-bb7a-11ec-945b-9fff29d6da48-0 tested green

/lgtm

**Comment by deads2k** [comment]
no bug needed for landing in master

**Comment by hasbro17** [comment]
/retitle Bug 2063831: Replace quorumguard and add readyz server

**Pull request merged**
