### PR TITLE
OCPBUGS-23106: [4.13] Remove z-upgrades from UpgradeBackupController

### PR DESCRIPTION
**Pull request by tjungblu**

### CODE REVIEW

**Review by geliu2016 — APPROVED** [review]
/label cherry-pick-approved

**Comment by tjungblu** [comment]
/hold

this needs the fix from #1176 potentially

**Comment by tjungblu** [comment]
added the fix from #1176

/jira refresh

**Comment by tjungblu** [comment]
@sandeepknd if you still have capacity, let's also continue here. I've added the fix we applied to 4.14 here as well.

@Elbehery need a BPA + review please :)

**Pull request merged**
