### PR TITLE
bug 2064024: Update library-go to 80f9619c2

### PR DESCRIPTION
**Pull request by pacevedom**
Relates to https://github.com/openshift/library-go/pull/1347, where we increase missing static pods timeout in case we are in single node.

### CODE REVIEW

**Comment by ingvagabund** [comment]
/retitle bug 2064024: Update library-go to 80f9619c2

**Comment by Elbehery** [comment]
@ingvagabund hello :) .. can u rebase the branch to fix the tide ?

**Review by Elbehery — APPROVED** [review]
/lgtm

**Pull request merged**
