### PR TITLE
Bug 2063183: Upping defrag timeout to 1 minute

### PR DESCRIPTION
**Pull request by dusk125**
https://bugzilla.redhat.com/show_bug.cgi?id=2063183

### CODE REVIEW

**Comment by dusk125** [comment]
/retitle Bug 2063183: Upping defrag timeout to 1 minute

**Comment by tjungblu** [comment]
That's sane and a better setting for sure. 
We have a fully blown mitigation for the customer in https://github.com/openshift/cluster-etcd-operator/pull/810 as well

/lgtm
/retest-required

**Review by geliu2016 — APPROVED** [review]
/lgtm
/label cherry-pick-approved

**Pull request merged**
