### PR TITLE
Bug 1880313: vendor: bump k8s to 1.18.6 to fix bug in reflector not recovering from "Too large resource version"

### PR DESCRIPTION
**Pull request by hexfusion**
Signed-off-by: Sam Batschelet <sbatsche@redhat.com>

### CODE REVIEW

**Comment by hexfusion** [comment]
cc @p0lyn0mial re bug fix landed in `1.18.6` since we have not bumped o/k is it a valid fix to just bump kube as U did here in your opinion?

**Comment by p0lyn0mial** [comment]
o/k is updated here - https://github.com/openshift/origin/pull/25489

**Comment by markmc** [comment]
/retitle Bug 1880313: vendor: bump k8s to 1.18.6 to fix bug in reflector not recovering from "Too large resource version"

**Comment by hexfusion** [comment]
thanks for the assist @markmc

**Pull request merged**
