### PR TITLE
bug 1801397: use a static pod manager

### PR DESCRIPTION
**Pull request by deads2k**
This PR bring all the disparate parts together to see if we can get the whole up and running.

### CODE REVIEW

**Comment by deads2k** [comment]
spoke on slack with @hexfusion .  This passed bootstrapping last run.  Found a condition ordering problem and fixed it.

We will go with this as soon as it can merge and build out from here.  This unblocks
 1. removing DNS from startup flow
 2. fixing etcd member name to be node names
 3. removing DNS from kas flow
 4. removing old daemonset sync and status daemonsets

**Comment by hexfusion** [comment]
/lgtm

:1st_place_medal:

**Comment by deads2k** [comment]
/hold

:(

Operator reported green, but bootstrapping failed

**Comment by deads2k** [comment]
gcp lost all kube-apiservers in https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_cluster-etcd-operator/112/pull-ci-openshift-cluster-etcd-operator-master-e2e-gcp/372

/retest

**Comment by alaypatel07** [comment]
```
I0213 17:43:18.371106       1 balancer_conn_wrappers.go:127] pickfirstBalancer: HandleSubConnStateChange: 0xc0019c4a90, CONNECTING
I0213 17:43:18.463784       1 balancer_conn_wrappers.go:127] pickfirstBalancer: HandleSubConnStateChange: 0xc0019c4a90, READY
E0213 17:43:18.467850       1 runtime.go:78] Observed a panic: runtime.boundsError{x:0, y:0, signed:true, code:0x0} (runtime error: index out of range [0] with length 0)
goroutine 862 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1f29340, 0xc00188aba0)
        k8s.io/apimachinery@v0.17.1/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        k8s.io/apimachinery@v0.17.1/pkg/util/runtime/runtime.go:48 +0x82
panic(0x1f29340, 0xc00188aba0)
        runtime/panic.go:679 +0x1b2
github.com/openshift/cluster-etcd-operator/pkg/operator/clustermembercontroller2.(*ClusterMemberController).areAllEtcdMembersHealthy(0xc000784640, 0x404000, 0x0, 0x0)
        github.com/openshift/cluster-etcd-operator@/pkg/operator/clustermembercontroller2/clustermembercontroller.go:301 +0x5c1
github.com/openshift/cluster-etcd-operator/pkg/operator/clustermembercontroller2.(*ClusterMemberController).reconcileMembers(0xc000784640, 0xc00033d200, 0xc000679b30)
        github.com/openshift/cluster-etcd-operator@/pkg/operator/clustermembercontroller2/clustermembercontroller.go:157 +0x43
github.com/openshift/cluster-etcd-operator/pkg/operator/clustermembercontroller2.(*ClusterMemberController).sync(0xc000784640, 0x1cfcf40, 0x23f89c0)
        github.com/openshift/cluster-etcd-operator@/pkg/operator/clustermembercontroller2/clustermembercontroller.go:133 +0x40
github.com/openshift/cluster-etcd-operator/pkg/operator/clustermembercontroller2.(*ClusterMemberController).processNextWorkItem(0xc000784640, 0xc000f28800)
        github.com/openshift/cluster-etcd-operator@/pkg/operator/clustermembercontroller2/clustermembercontroller.go:120 +0xd5
github.com/openshift/cluster-etcd-operator/pkg/operator/clustermembercontroller2.(*ClusterMemberController).runWorker(0xc000784640)
        github.com/openshift/cluster-etcd-operator@/pkg/operator/clustermembercontroller2/clustermembercontroller.go:109 +0x2b
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0018e3a20)
        k8s.io/apimachinery@v0.17.1/pkg/util/wait/wait.go:152 +0x5e
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0018e3a20, 0x3b9aca00, 0x0, 0x1, 0xc0000b5f20)
        k8s.io/apimachinery@v0.17.1/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(0xc0018e3a20, 0x3b9aca00, 0xc0000b5f20)
        k8s.io/apimachinery@v0.17.1/pkg/util/wait/wait.go:88 +0x4d
created by github.com/openshift/cluster-etcd-operator/pkg/operator/clustermembercontroller2.(*ClusterMemberController).Run
        github.com/openshift/cluster-etcd-operator@/pkg/operator/clustermembercontroller2/clustermembercontroller.go:99 +0x205
I0213 17:43:18.467876       1 controlbuf.go:508] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
I0213 17:43:18.467921       1 controlbuf.go:508] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
I0213 17:43:18.468098       1 controlbuf.go:508] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
```
Observed a panic when running this manually, not sure what is wrong but digging

**Comment by alaypatel07** [comment]
was using a stale version of this PR in https://github.com/openshift/cluster-etcd-operator/pull/112#issuecomment-585883287, ignore

**Comment by deads2k** [comment]
hit https://github.com/openshift/cluster-etcd-operator/pull/144 on gcp

hit https://github.com/openshift/machine-config-operator/pull/1473 on aws

**Comment by deads2k** [comment]
`[Conformance][Area:Networking][Feature:Router] The HAProxy router [Top Level] [Conformance][Area:Networking][Feature:Router] The HAProxy router should serve the correct routes when running with the haproxy config manager [Suite:openshift/conformance/parallel/minimal]
`
/retest

**Comment by deads2k** [comment]
hit openshift/machine-config-operator#1473 on azure.

**Comment by deads2k** [comment]
Infra

/Lgtm

**Comment by deads2k** [comment]
Alert
/Retest

**Comment by deads2k** [comment]
superceded by https://github.com/openshift/cluster-etcd-operator/pull/142

**Pull request closed without merging**
