### PR TITLE
pkg/etcdenvvar: set periodical watch progress notification to 5s

### PR DESCRIPTION
**Pull request by hexfusion**
While this ENV is currently marked experimental it has large positive performance impacts[1]. Upstream kep[2].

cc @deads2k 

[1] https://github.com/kubernetes/kubernetes/pull/99021/files#diff-53f602f80b466ce021d5d5f8b14894997ccde64ae4d9b207296c3ca49978bdfbR555
[2] https://github.com/kubernetes/enhancements/tree/master/keps/sig-api-machinery/1904-efficient-watch-resumption

### CODE REVIEW

**Comment by deads2k** [comment]
/lgtm
/hold

let's get up to the latest 3.4.z first, then re-test this.  

The before: https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/1904-efficient-watch-resumption/without_feature_metrics.png

and after: https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/1904-efficient-watch-resumption/with_feature_metrics.png

show significant smoothing and latency improvements on large clusters.

**Comment by hexfusion** [comment]
/test all
/hold cancel

cc @deads2k

**Comment by hexfusion** [comment]
cc @sttts

**Comment by hexfusion** [comment]
cc @tkashem

**Comment by hexfusion** [comment]
/hold 

upgrade apiserver downtime looks horrible[1] going to review that.

[1] https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-etcd-operator/548/pull-ci-openshift-cluster-etcd-operator-master-e2e-agnostic-upgrade/1366709061281648640

/retest

**Comment by hexfusion** [comment]
/hold cancel

the upgrade API latencies are observed before this PR[1] in nightly so unrelated to this change.

[1] https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-ocp-installer-e2e-aws-upgrade-4.8/1366564467134959616

**Pull request merged**
