### PR TITLE
ETCD-695: Add job parallelism to recurrent backups

### PR DESCRIPTION
**Pull request by Elbehery**
resolves https://issues.redhat.com/browse/ETCD-695

cc @tjungblu @JoelSpeed

### CODE REVIEW

**Comment by JoelSpeed** [comment]
Changes look like the right sort of thing from scheduling perspective, how does the persistent volume side of this work? Do we need to be able to test this with a local path directly?

**Comment by Elbehery** [comment]
> Changes look like the right sort of thing from scheduling perspective, how does the persistent volume side of this work? Do we need to be able to test this with a local path directly?

so I used a `localVolume` storage class

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
```

But the `Backup`  [CR](https://github.com/openshift/api/blob/684b2b1679baeb7742ec7b76c6eab8e0c8036e56/config/v1alpha1/types_backup.go#L99) expects a `PVC` per `CR`, this is not possible here, since we need 3 different PVCs, one per each node, before hand

In order to get this approach working properly, we need a new API, where the PVC field is a slice, and gets a PVC per each master  node in the cluster

**Comment by JoelSpeed** [comment]
> In order to get this approach working properly, we need a new API, where the PVC field is a slice, and gets a PVC per each master node in the cluster

Or for testing this theory, just set a hostvolume and privilege directly onto the pod spec, and don't worry about the PVC

**Comment by JoelSpeed** [comment]
What was the conclusion of this experiment?

**Comment by Elbehery** [comment]
But the `Backup`  [CR](https://github.com/openshift/api/blob/684b2b1679baeb7742ec7b76c6eab8e0c8036e56/config/v1alpha1/types_backup.go#L99) expects a `PVC` per `CR`, this is not possible here, since we need 3 different PVCs, one per each node, before hand

In order to get this approach working properly, we need a new API, where the PVC field is a slice, and gets a PVC per each master  node in the cluster

**Comment by JoelSpeed** [comment]
Did you try https://github.com/openshift/cluster-etcd-operator/pull/1363#issuecomment-2444641024? 

When we discussed this on the call, we knew that the PVC thing was going to be an issue, so we said that we should test the cronjob parallelism without using PVCs, to see if the mechanics of scheduling and completions worked in our favour.

It appears to me that you were testing it with PVCs, and hit a wall, and didn't actually get to testing the cronjob features we wanted to experiment with? Or at least, from reading threads here and on the EP, that's all I can see.

I remember suggesting on the call to add an alternative option to the PVC, which would allow users to configure backups to be taken on localvolume. When configured as localvolume backups, this would then automatically use the parallelism and completions features to make sure we ran the correct number of jobs for the expected number of control plane nodes. I thought at a group we had agreed on that as an idea for a direction?

**Comment by Elbehery** [comment]
I recall that I have tried to patch the pods with hostPath, I don't remember why it failed ..

Do u wanna hop on call and try it together ?

**Pull request closed without merging**
