### PR TITLE
Bug 1837630: pkg/operator/etcdcertsigner: sign etcd certs for 3 years

### PR DESCRIPTION
**Pull request by hexfusion**
Cherry-pick of https://github.com/openshift/cluster-etcd-operator/pull/356

Signed-off-by: Sam Batschelet <sbatsche@redhat.com>

### CODE REVIEW

**Comment by hexfusion** [comment]
> @hexfusion: you cannot LGTM your own PR.

busted..

**Comment by hexfusion** [comment]
cc @sdodson 

+1 for 4.4 backport.

**Comment by ashcrow** [comment]
@sdodson do you mind adding the cherrypick approved label here? I approve of this but don't have the access yet for this repo.

**Pull request merged**
