### PR TITLE
bug 1802245: fix host endpoint hotloop

### PR DESCRIPTION
**Pull request by deads2k**
evidence of hotloop here https://prow.svc.ci.openshift.org/pr-history/?org=openshift&repo=cluster-etcd-operator&pr=123

Removes dead removal code and sets up custom equality check to take control of equality.

### CODE REVIEW

**Comment by deads2k** [comment]
/hold 

for hotloop proof

**Comment by deads2k** [comment]
Didn't work.  We still have hundreds of these

```
Event(v1.ObjectReference{Kind:"Deployment", Namespace:"openshift-etcd-operator", Name:"etcd-operator", UID:"0d587cc1-38e4-4c5e-9bc0-27ed97f57794", APIVersion:"apps/v1", ResourceVersion:"", FieldPath:""}): type: 'Warning' reason: 'EndpointsUpdated' Updated endpoints/host-etcd -n openshift-etcd because it changed: {"subsets":[{"addresses":[{"hostname":"etcd-0","ip":"10.0.0.4","nodeName":"ci-op-k2kj4-m-0.c.openshift-gce-devel-ci.internal"},{"hostname":"etcd-1","ip":"10.0.0.3","nodeName":"ci-op-k2kj4-m-1.c.openshift-gce-devel-ci.internal"},{"hostname":"etcd-2","ip":"10.0.0.5","nodeName":"ci-op-k2kj4-m-2.c.openshift-gce-devel-ci.internal"},{"hostname":"etcd-bootstrap","ip":"10.0.0.6"}],"ports":[{"name":"etcd","port":2379,"protocol":"TCP"}]}]}
```

**Comment by deads2k** [comment]
found it: https://github.com/kubernetes/kubernetes/blob/4271384966e34baddabda61e370311e9ea4bbf6c/pkg/registry/core/endpoint/strategy.go#L62-L65

**Comment by sanchezl** [comment]
@see https://github.com/openshift/cluster-etcd-operator/pull/131

**Pull request closed without merging**
