### PR TITLE
bindata/etcd: Enable gRPC time histograms

### PR DESCRIPTION
**Pull request by lilic**
Wanted to see the latency metrics and noticed we do not have those enabled in OpenShift. This is more aimed at 4.9, opening to check the number of series this adds to cluster Prometheus but also to not forget to enable. :)

This allows us to measure latency distributions of the RPCs. This brings in the following histogram metrics:
* grpc_server_handling_seconds_count
* grpc_server_handling_seconds_sum
* grpc_server_handling_seconds_bucket

/hold

### CODE REVIEW

**Comment by lilic** [comment]
This will also enable us to actually have a working alert around `etcdGRPCRequestsSlow `, as right now that doesn't work as the metrics are not there. https://github.com/openshift/cluster-monitoring-operator/blob/26055d081b12fd1909fb626a3df291f8b62635dd/assets/control-plane/etcd-prometheus-rule.yaml#L54-L64

**Comment by lilic** [comment]
/retest

This is a known failure "ci/prow/e2e-gcp-five-control-plane-replicas".

@openshift/openshift-team-monitoring please take a look, this introduces extra series to Prometheus, but also enables the alert `etcdGRPCRequestsSlow` that did not work before.

**Comment by hexfusion** [comment]
/override ci/prow/e2e-gcp-five-control-plane-replicas
/approve

@openshift/openshift-team-monitoring please LGTM

**Comment by lilic** [comment]
/hold cancel

> The etcdGRPCRequestsSlow alert description could state the percentile value IMHO. It could say something like "99% of gRPC requests to ... are taking more than ... seconds ...".

Thanks Simon, will adjust the alert, plan was to just migrate the alerts and adjust them later but agreed 💯

**Comment by hexfusion** [comment]
/overrride ci/prow/e2e-gcp-five-control-plane-replicas


<br class="Apple-interchange-newline">

**Pull request merged**
