### PR TITLE
OCPBUGS-22477: Remove z-upgrades from UpgradeBackupController

### PR DESCRIPTION
**Pull request by tjungblu**
This removes the z-upgrade trigger for the UpgradeBackupControllers again and adds a front-running retention by deleting all existing backups before taking a new backup.

### CODE REVIEW

**Comment by Elbehery** [comment]
@tjungblu  verify-deps fails on 

```
< 	github.com/mcuadros/go-version v0.0.0-20190830083331-035f6764e8d2
`go.mod` content is incorrect - did you run `go mod tidy`?
```

**Comment by tjungblu** [comment]
/hold

need to test this still

**Comment by tjungblu** [comment]
briefly testing this from 4.14.0 to 4.14.1, upgrade backup controller does not attempt to take any snapshot and the upgrade proceeds.

Still need to test the serial upgrades and y upgrades, the latter didn't work yesterday.

**Comment by tjungblu** [comment]
y-upgrade to 4.15 does trigger a snapshot (wrong). I think it's because the z-upgrade to 4.14.1 is simply overriding the CEO image. Gotta check how I can do it without merging this first. Otherwise I need to create a new cluster everytime :roll_eyes:

**Review by geliu2016 — APPROVED** [review]
/label cherry-pick-approved

**Pull request merged**
