### PR TITLE
Revert "OCPBUGS-30169: add timeout to etcd client.New config"

### PR DESCRIPTION
**Pull request by tjungblu**
Reverts openshift/cluster-etcd-operator#1215

### CODE REVIEW

**Review by geliu2016 — APPROVED** [review]
/label cherry-pick-approved

**Comment by tjungblu** [comment]
omfg :rofl: retesting again

**Comment by tjungblu** [comment]
I'll override this clear waste of money of testing a revert the 200th time

/override ci/prow/e2e-agnostic-ovn
/override ci/prow/e2e-agnostic-ovn-upgrade 
/override ci/prow/e2e-aws-ovn-etcd-scaling
/override ci/prow/e2e-operator

**Pull request merged**
