### PR TITLE
Add IBM Cloud managed annotations to CVO manifests

### PR DESCRIPTION
**Pull request by csrwng**
This matches https://github.com/openshift/enhancements/pull/445 and does not change behavior.

### CODE REVIEW

**Comment by ironcladlou** [comment]
@csrwng was the dependency bump intended and/or necessary for this change?

**Comment by csrwng** [comment]
> @csrwng was the dependency bump intended and/or necessary for this change?

@ironcladlou yes it was necessary so we could pick up the updated `vendor/github.com/openshift/api/operator/v1/0000_12_etcd-operator_01_config.crd.yaml` file from github.com/openshift/api

**Pull request merged**
