### PR TITLE
OCPBUGS-17199: remove stability check from bootstrap completeness

### PR DESCRIPTION
**Pull request by jubittajohn**

### CODE REVIEW

**Comment by tjungblu** [comment]
Thanks for trying this out again @jubittajohn. Good to see the ass. Installer working still with this change.

/hold
/lgtm

Feel free to cancel the hold once you're ready.

**Comment by jubittajohn** [comment]
Tested the change twice against a cluster and the following case is working fine:

- Stop the kubelet on a node. The node becomes Not Ready.
- Delete the machine hosting the above node.
- The deleted machine is no more stuck in deleting state and is successfully removed and a new machine is created. (CPMS enabled).

cancelling hold.
/hold cancel

**Comment by tjungblu** [comment]
/cherry-pick release-4.17 release-4.16 release-4.15 release-4.14

**Pull request merged**
