### PR TITLE
Bug 1859678: Forget bootstrap etcd member IP after bootstrap

### PR DESCRIPTION
**Pull request by palonsoro**
After bootstrap completes, forget the bootstrap etcd member IP by clearing
the annotation from the endpoint configmap. Otherwise the etcd client will
continue failing to connect to the dead bootstrap node forever.

Backport to 4.5.z

### CODE REVIEW

**Comment by hexfusion** [comment]
etcdctl fix is here[1] we will look at this as well.

https://github.com/openshift/cluster-etcd-operator/pull/402

**Comment by ironcladlou** [comment]
@palonsoro thanks for putting this together!

/approve

**Pull request merged**
