### PR TITLE
Revert "Integrate feature flags in CEO"

### PR DESCRIPTION
**Pull request by DennisPeriquet**
Reverts openshift/cluster-etcd-operator#1062

Per [Openshift policy](https://github.com/openshift/enhancements/blob/master/enhancements/release/improving-ci-signal.md#quick-revert) we are reverting this breaking change to get CI and/or nightly payloads flowing again.

This change is breaking
* 4.14 CI payload: 4.14.0-0.ci-2023-07-08-062054
* 4.14 nightly payload: 4.14.0-0.nightly-2023-07-08-161537

To unrevert this, revert this PR, and layer an additional separate commit on top that addresses the problem. Before merging the unrevert, please run these jobs on the PR and check the result of to confirm the fix has corrected the problem:

/payload 4.14 nightly blocking
/payload 4.14 nightly ci

Since this PR was [introduced](https://sippy.dptools.openshift.org/sippy-ng/pull_requests/Presubmits?filters=%257B%2522items%2522%253A%255B%257B%2522columnField%2522%253A%2522number%2522%252C%2522operatorValue%2522%253A%2522equals%2522%252C%2522value%2522%253A%25221062%2522%257D%252C%257B%2522columnField%2522%253A%2522repo%2522%252C%2522operatorValue%2522%253A%2522equals%2522%252C%2522value%2522%253A%2522cluster-etcd-operator%2522%257D%255D%252C%2522linkOperator%2522%253A%2522and%2522%257D), [4.14.0-0.ci-2023-07-08-062054](https://amd64.ocp.releases.ci.openshift.org/releasestream/4.14.0-0.ci/release/4.14.0-0.ci-2023-07-08-062054) and [4.14.0-0.nightly-2023-07-08-161537](https://amd64.ocp.releases.ci.openshift.org/releasestream/4.14.0-0.nightly/release/4.14.0-0.nightly-2023-07-08-161537) have gotten this failure:

```
Failed: suite=[openshift-tests-upgrade], [sig-cluster-lifecycle] pathological event should not see excessive Back-off restarting failed containers
```

Given a sample failure like [this](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-ci-4.14-upgrade-from-stable-4.13-e2e-aws-ovn-upgrade/1677565798861770752) and [logs](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/periodic-ci-openshift-release-master-ci-4.14-upgrade-from-stable-4.13-e2e-aws-ovn-upgrade/1677565798861770752/artifacts/e2e-aws-ovn-upgrade/gather-extra/artifacts/pods/openshift-etcd-operator_etcd-operator-97848f-mftsx_etcd-operator_previous.log) like this:

```
E0708 09:38:50.892701       1 simple_featuregate_reader.go:290] cluster failed with : unable to determine features: missing desired version "4.13.0-0.ci-2023-07-07-163417" in featuregates.config.openshift.io/cluster
```

I believe this PR is the cause.

cc @tjungblu

### CODE REVIEW

**Comment by neisw** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.14-upgrade-from-stable-4.13-e2e-aws-ovn-upgrade

**Comment by tjungblu** [comment]
Thanks, let's get this in for now - I'll revise this later.

**Pull request merged**
