### PR TITLE
Bug 1874597: static-pod-installer: remove deadlock by recreating installers that disappear

### PR DESCRIPTION
**Pull request by hexfusion**
Signed-off-by: Sam Batschelet <sbatsche@redhat.com>

### CODE REVIEW

**Comment by hexfusion** [comment]
cc @sdodson

**Comment by sdodson** [comment]
> cc @sdodson

Thanks, I'm interested in this because it's halted upgrades but I'm not patch manager right now so another patch manager will hopefully approve this Wed - Friday.

**Comment by markmc** [comment]
Helpful to reference the original openshift/library-go#871 which has more background on the issue

**Comment by sdodson** [comment]
> Helpful to reference the original [openshift/library-go#871](https://github.com/openshift/library-go/pull/871) which has more background on the issue

And the upstream PR for this repo too https://github.com/openshift/cluster-etcd-operator/pull/431

**Pull request merged**
