### PR TITLE
OCPBUGS-31658: Fix feature set custom no upgrade

### PR DESCRIPTION
**Pull request by vr4manta**
[OCPBUGS-31658](https://issues.redhat.com/browse/OCPBUGS-31658)

### Changes
- Updated API to get new manifests
- Updated dockerfile to use new manifest files

### Notes
Altinfra tests have been failing due to use of CustomNoUpgrade feature set.  The etcd operator's CRD is not being installed for CustomNoUpgrade due to the CustomNoUpgrade manifest missing.

### CODE REVIEW

**Comment by vr4manta** [comment]
/payload-job pull-ci-openshift-installer-master-altinfra-e2e-vsphere-capi-ovn

**Review by geliu2016 — APPROVED** [review]
/lgtm

**Comment by vr4manta** [comment]
/assign @hasbro17 
Some tests are failing but I do not think they are related to these changes.  Let me know your thoughts.

**Comment by tjungblu** [comment]
Thanks for fixing it, I'm not sure what went missing in the first place, but I don't want to hold this up any longer for you folks.

/approve

unrelated test failures:

/override ci/prow/e2e-aws-ovn-etcd-scaling
/override ci/prow/e2e-operator-fips

**Pull request merged**
