### PR TITLE
Fix deps for new CI

### PR DESCRIPTION
**Pull request by tnozicka**
We need https://github.com/openshift/library-go/pull/218 to get a fix for validating vendor/ directory to pass CI.

/cc @deads2k @hexfusion

### CODE REVIEW

**Comment by tnozicka** [comment]
/hold
seems like we need to deal with glide not properly managing mercurial, will use this as a playground for a while :)

**Comment by hexfusion** [comment]
Just noticed a few text files in the vendor is that something we generally vet?

**Comment by tnozicka** [comment]
@hexfusion vendor/ is whatever `glide` puts there, we shouldn't touch it - and there is now a CI check to enforce it. also we don't prune vendor to used files only otherwise you'd have to be changing deps with every second change in /pkg ;)

**Comment by hexfusion** [comment]
@tnozicka ok that is fine I manage/vet these non go files in other packages just checking protocol here, thanks.

**Pull request merged**
