### PR TITLE
OCPBUGS-2852: later bootstrap removal in delayed scaling

### PR DESCRIPTION
**Pull request by tjungblu**

### CODE REVIEW

**Comment by tjungblu** [comment]
seems fixed by https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-origin-installer-launch-metal/1594654811779764224

**Comment by hasbro17** [comment]
/lgtm
/retest-required

The `alert/KubePodNotReady` failure in [e2e-agnostic-ovn-upgrade](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-etcd-operator/964/pull-ci-openshift-cluster-etcd-operator-master-e2e-agnostic-ovn-upgrade/1594653200722432000) is known and unrelated. We can override if it blocks again.

**Review by geliu2016 — APPROVED** [review]
/lgtm
/label cherry-pick-approved

**Pull request merged**
