### PR TITLE
WIP: experiment with a render command for an all-in-one config

### PR DESCRIPTION
**Pull request by markmc**
This is just some early-stage hacking to see a render command for an all-in-one config might look like.

As such this is related to openshift/enhancements#302 but a much hackier approach to what's described there.

### CODE REVIEW

**Comment by hexfusion** [comment]
cc @ironcladlou

**Comment by ironcladlou** [comment]
@markmc thanks for putting this together! Your work here with certificate rendering actually intersects with some tech debt we've been meaning to pay down in bootstrapping, which currently generates certificates using a potentially flaky client/server model that's now unnecessary.

I need to open a separate set of PRs for that work (in the operator and the installer) and I'll keep your PR in mind while doing so (I haven't had a chance to look closely at what you've done, it's possible you may have given me a head start).

Once I have a WIP going I'll link it to this PR. I want to make sure what I'm doing is reusable in the context of your AIO goals.

**Comment by markmc** [comment]
Work along these lines is happening at openshift/enhancements#440 now

**Pull request closed without merging**
