### PR TITLE
OCPBUGS-21846: sync(library-go): revision_controller: update last revision only when a revision is completely rendered

### PR DESCRIPTION
**Pull request by ingvagabund**
Pulling https://github.com/openshift/library-go/pull/1651

### CODE REVIEW

**Comment by tjungblu** [comment]
trying again for an updated image:

/retest-required

**Comment by tjungblu** [comment]
okay seems to be a 1.20 vs 1.21 thing, I also have the same issue in #1177 with my own update.

@ingvagabund do you mind if I upgrade for you? I need to pull in changes from https://github.com/openshift/library-go/pull/1653

**Comment by ingvagabund** [comment]
By all means :)

**Comment by ingvagabund** [comment]
Closing in favor of https://github.com/openshift/cluster-etcd-operator/pull/1180

**Pull request closed without merging**
