### PR TITLE
[release-4.11] OCPBUGS-9908: Garbage collect grafana-dashboard-etcd

### PR DESCRIPTION
**Pull request by Elbehery**
this is a manual cherrypick of https://github.com/openshift/cluster-etcd-operator/pull/1016

resolves https://issues.redhat.com/browse/OCPBUGS-9908

### CODE REVIEW

**Comment by tjungblu** [comment]
actually, we might not need this in 4.10, correct?

**Comment by Elbehery** [comment]
> actually, we might not need this in 4.10, correct?

No, I think only till 4.11 iiuc 

cc @wking

**Comment by Elbehery** [comment]
> /cherry-pick release-4.10

i tried `/cherry-pick cancel` but it is wrong :D .. how to cancel this ?

**Comment by Elbehery** [comment]
@geliu2016  can you label this & verify please ?

**Comment by Elbehery** [comment]
@geliu2016  can we verify this as well ? 

Please ignore `4.10` backport 👍🏽

**Pull request merged**
