### PR TITLE
Bug 2042501: bump library-go

### PR DESCRIPTION
**Pull request by tkashem**

### CODE REVIEW

**Comment by tkashem** [comment]
@dusk125 @hasbro17 looks like no e2e test is passing, it may be due to changes in this PR. can we debug this? Note that similar PR for kas operator has already merged - https://github.com/openshift/cluster-kube-apiserver-operator/pull/1294

Thanks!

**Comment by deads2k** [comment]
/hold

I'm holding this until we get resolution on https://coreos.slack.com/archives/C01CQA76KMX/p1642791722497600?thread_ts=1642786244.483900&cid=C01CQA76KMX

nag me on slack if you really really need it.

**Comment by hasbro17** [comment]
@tkashem We're getting a nil pointer dereference with this bump
```sh
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x1f5d1f7]

goroutine 297 [running]:
github.com/openshift/library-go/pkg/operator/staticpod.(*staticPodOperatorControllerBuilder).ToControllers(0xc000824820)
	github.com/openshift/library-go@v0.0.0-20220117173518-ca57b619b5d6/pkg/operator/staticpod/controllers.go:293 +0xf57
github.com/openshift/cluster-etcd-operator/pkg/operator.RunOperator({0x2980738, 0xc000902140}, 0xc0005c61c0)
	github.com/openshift/cluster-etcd-operator/pkg/operator/starter.go:159 +0xc13
github.com/openshift/library-go/pkg/controller/controllercmd.ControllerBuilder.getOnStartedLeadingFunc.func1.1()
	github.com/openshift/library-go@v0.0.0-20220117173518-ca57b619b5d6/pkg/controller/controllercmd/builder.go:351 +0x74
created by github.com/openshift/library-go/pkg/controller/controllercmd.ControllerBuilder.getOnStartedLeadingFunc.func1
	github.com/openshift/library-go@v0.0.0-20220117173518-ca57b619b5d6/pkg/controller/controllercmd/builder.go:349 +0x10f
```

Specifically it seems like we need to account for the library-go change to set the `operandPodLabelSelector` via `WithOperandPodLabelSelector()` when building the staticpod controller.
https://github.com/openshift/cluster-etcd-operator/blob/fba95469a283cc0b872be4ac95f2a2ecfd4af4f2/vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go#L91

https://github.com/openshift/library-go/commit/4c466c21debfef89e73e28b59b46937ca1b9034c#diff-d0ce926df996bfa572967a0d2a1d011bbfc84cd41e065b957328285647b17cec

Before this change I don't think we're initializing this anywhere so I'm a little unclear on what that's for exactly.
https://github.com/openshift/cluster-etcd-operator/blob/14fecbd21d47fe19ab0219f59a10a0bbd4dc67ea/pkg/operator/starter.go#L152-L162

**Comment by p0lyn0mial** [comment]
> @tkashem We're getting a nil pointer dereference with this bump
> 
> ```shell
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x1f5d1f7]
> 
> goroutine 297 [running]:
> github.com/openshift/library-go/pkg/operator/staticpod.(*staticPodOperatorControllerBuilder).ToControllers(0xc000824820)
> 	github.com/openshift/library-go@v0.0.0-20220117173518-ca57b619b5d6/pkg/operator/staticpod/controllers.go:293 +0xf57
> github.com/openshift/cluster-etcd-operator/pkg/operator.RunOperator({0x2980738, 0xc000902140}, 0xc0005c61c0)
> 	github.com/openshift/cluster-etcd-operator/pkg/operator/starter.go:159 +0xc13
> github.com/openshift/library-go/pkg/controller/controllercmd.ControllerBuilder.getOnStartedLeadingFunc.func1.1()
> 	github.com/openshift/library-go@v0.0.0-20220117173518-ca57b619b5d6/pkg/controller/controllercmd/builder.go:351 +0x74
> created by github.com/openshift/library-go/pkg/controller/controllercmd.ControllerBuilder.getOnStartedLeadingFunc.func1
> 	github.com/openshift/library-go@v0.0.0-20220117173518-ca57b619b5d6/pkg/controller/controllercmd/builder.go:349 +0x10f
> ```
> 
> Specifically it seems like we need to account for the library-go change to set the `operandPodLabelSelector` via `WithOperandPodLabelSelector()` when building the staticpod controller.
> 
> https://github.com/openshift/cluster-etcd-operator/blob/fba95469a283cc0b872be4ac95f2a2ecfd4af4f2/vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go#L91
> 
> [openshift/library-go@4c466c2#diff-d0ce926df996bfa572967a0d2a1d011bbfc84cd41e065b957328285647b17cec](https://github.com/openshift/library-go/commit/4c466c21debfef89e73e28b59b46937ca1b9034c#diff-d0ce926df996bfa572967a0d2a1d011bbfc84cd41e065b957328285647b17cec)
> 
> Before this change I don't think we're initializing this anywhere so I'm a little unclear on what that's for exactly.
> 
> https://github.com/openshift/cluster-etcd-operator/blob/14fecbd21d47fe19ab0219f59a10a0bbd4dc67ea/pkg/operator/starter.go#L152-L162

callers should not be required to specify ` WithOperandPodLabelSelector`, controllers that require the selector should report an error when the selector wasn't provided. 

working on a fix . . .

**Comment by deads2k** [comment]
we have enough history to call https://bugzilla.redhat.com/show_bug.cgi?id=2040533 fixed.  I'm releasing this hold

/hold cancel

**Pull request merged**
