### PR TITLE
OCPBUGS-1014: avoid extrapolation in leaderhip alert

### PR DESCRIPTION
**Pull request by Elbehery**
Manual cherrypick of https://github.com/openshift/cluster-etcd-operator/pull/851

### CODE REVIEW

**Comment by tjungblu** [comment]
/lgtm

Thanks Mustafa! I think for the jira bot we either need a fake 4.10 that we manually set to complete or @hasbro17 can label the PR as valid :D

**Comment by Elbehery** [comment]
> /lgtm
> 
> Thanks Mustafa! I think for the jira bot we either need a fake 4.10 that we manually set to complete or @hasbro17 can label the PR as valid :D

thats what I was doing now :D

**Comment by tjungblu** [comment]
yeah it's a pain, that's why I want to close out all bugs in BZ....

**Comment by Elbehery** [comment]
> yeah it's a pain, that's why I want to close out all bugs in BZ....

yes we need to focus on JIRA only :D

**Comment by Elbehery** [comment]
> /cherry-pick release-4.8

it will fail due to conflicts .. i will do it manually 👍🏽

**Comment by tjungblu** [comment]
ahh alrighty! thanks

**Comment by Elbehery** [comment]
> ahh alrighty! thanks

can u cancel the automated cherrypick ?

**Comment by tjungblu** [comment]
lol, never tried. But if you say it fails then it will not do much.

**Comment by tjungblu** [comment]
yep

**Pull request closed without merging**
