### PR TITLE
[release-4.4] Bug 1877965: Use restore pod yaml from the backup when restoring

### PR DESCRIPTION
**Pull request by retroflexer**
Ths is a manual cherry-pick of #436  and an additional commit to include a fallback mechanism to copy restore pod yaml from local disk, if the backup doesn't contain it. 

This is done to support backups that were taken before the change to include restore-pod yaml in the static-pod-resources of etcd.

The commits are identcal to #442 submitted to release-4.5.

### CODE REVIEW

**Comment by retroflexer** [comment]
Manually installed a cluster with this PR, and verified that the backup and restore procedures work as expected.

Also verified that the restore-etcd-pod is copied from the static-resources archive during the restore, instead of using the latest on disk.

```
core@ip-10-0-161-221 ~]$ sudo /usr/local/bin/cluster-backup.sh mybackup1
0c08c62a8f8ad1c45c1cb9b38a9216b704ba6a446d08295de57f696d51e34370
etcdctl version: 3.3.22
API version: 3.3
found latest kube-apiserver-pod: /etc/kubernetes/static-pod-resources/kube-apiserver-pod-7
found latest kube-controller-manager-pod: /etc/kubernetes/static-pod-resources/kube-controller-manager-pod-8
found latest kube-scheduler-pod: /etc/kubernetes/static-pod-resources/kube-scheduler-pod-6
found latest etcd-pod: /etc/kubernetes/static-pod-resources/etcd-pod-2
2020-10-09 20:01:44.250592 I | clientv3: opened snapshot stream; downloading
2020-10-09 20:01:45.096970 I | clientv3: completed snapshot read; closing
Snapshot saved at mybackup1/snapshot_2020-10-09_200143.db
snapshot db and kube resources are successfully saved to mybackup1
[core@ip-10-0-161-221 ~]$ tar tvzf mybackup1/static_kuberesources_2020-10-09_200143.tar.gz | grep restore
drwxr-xr-x root/root         0 2020-10-09 18:09 static-pod-resources/etcd-pod-2/configmaps/restore-etcd-pod/
-rw-r--r-- root/root         0 2020-10-09 18:09 static-pod-resources/etcd-pod-2/configmaps/restore-etcd-pod/forceRedeploymentReason
-rw-r--r-- root/root      7406 2020-10-09 18:09 static-pod-resources/etcd-pod-2/configmaps/restore-etcd-pod/pod.yaml
-rw-r--r-- root/root        27 2020-10-09 18:09 static-pod-resources/etcd-pod-2/configmaps/restore-etcd-pod/version


```

**Comment by retroflexer** [comment]
Eric Paris fixed the problem with bastion `ssh` deployment in 4.4 release using https://github.com/eparis/ssh-bastion/pull/29

Restarted the disruptive tests. Waiting for the results of those tests (although I manually verified the backup and restore).

**Comment by retroflexer** [comment]
Yay, e2e-aws-disruptive job is successfully finished! :+1:

**Comment by hexfusion** [comment]
@retroflexer please touch base with @stbenjam about the metal IPI test. My understanding is this test should not be blocking in 4.4. In which case we need to update it in openshift/release and either remove it or make it non-blocking in 4.4.

[1] https://github.com/openshift/release/blob/master/ci-operator/config/openshift/cluster-etcd-operator/openshift-cluster-etcd-operator-release-4.4.yaml#L77

**Comment by stbenjam** [comment]
We're looking into the 4.4 failures (BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1883660), but I'm comfortable with overriding e2e-metal-ipi on this PR. You're also welcome to make it optional on release-4.4, I don't think it's intentional we're blocking on this branch. But, please do check to make sure future failures aren't happening in etcd if e2e-metal-ipi fails.

**Comment by retroflexer** [comment]
> We're looking into the 4.4 failures (BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1883660), but I'm comfortable with overriding e2e-metal-ipi on this PR. You're also welcome to make it optional on release-4.4, I don't think it's intentional we're blocking on this branch. But, please do check to make sure future failures aren't happening in etcd if e2e-metal-ipi fails.

Thanks Steve. I made the tests optional (https://github.com/openshift/release/pull/12712) for now.

**Comment by retroflexer** [comment]
@hexfusion can you remove the hold?

/hold

**Comment by sdodson** [comment]
Clearing stale `cherry-pick-approved` will need to be re-evaluated.

**Comment by retroflexer** [comment]
@sdodson This PR was ready last week. The verify-deps were failing because bitbucket removed the dependent module. 

Now verify-deps is passing. Could you readd cherry-pick approved?

**Comment by retroflexer** [comment]
@hexfusion could you tag again?

**Comment by sdodson** [comment]
@retroflexer it'll have to catch the next merge window, which should be in just another day. As long as we're hitting our weekly merge schedules we'll avoid making any exceptions to accept changes merging after the window closes.

**Comment by hexfusion** [comment]
/hold 

for whatever reason, this will continue to retest metal-ipi when we are ready to merge unhold and `/skip`

**Comment by sdodson** [comment]
/skip
should work now

**Comment by sdodson** [comment]
Still lacks lgtm though, adding that may send it into a test loop but that's necessary before patch manager will consider it.

**Comment by hexfusion** [comment]
added it here I think prow is now working as expected.

https://github.com/openshift/cluster-etcd-operator/pull/443#issuecomment-707822528

/lgtm

**Pull request merged**
