### PR TITLE
Bug 1876484: static-pod-installer: remove deadlock by recreating installers that disappear

### PR DESCRIPTION
**Pull request by hexfusion**
cluster-etcd-operator uses k8s 1.18 in 4.4 because of the metrics controller deps[1]. To patch the bug referenced we bumped level with what was done to 4.5[1] . Also, this PR bumped 1.18 level with 4.5[2] to 1.18.6.

[1] https://github.com/openshift/cluster-etcd-operator/pull/365
[2] https://github.com/openshift/cluster-etcd-operator/pull/434
[3] https://github.com/openshift/cluster-etcd-operator/pull/447

Continued from #448

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/lgtm

**Comment by hexfusion** [comment]
/hold

@stbenjam and team are looking into metal-ipi failures.

cc @sdodson @markmc

**Comment by hexfusion** [comment]
/hold cancel

metal is non blocking

**Comment by hexfusion** [comment]
@markmc metal test unblocked. PTAL.

cc @sdodson

**Pull request merged**
