### PR TITLE
Bug 2073901: revisit defrag controller degradation

### PR DESCRIPTION
**Pull request by tjungblu**
only let the defrag controller degrade after failing several attempts at actual defragmentation work

### CODE REVIEW

**Comment by dusk125** [comment]
Thoughts on having the max failures configurable (maybe in the future) so if someone wants to degrade after 1 failure they could?

**Comment by tjungblu** [comment]
@dusk125 I like the idea, what would be a good way to configure this? via env vars?

**Comment by dusk125** [comment]
> @dusk125 I like the idea, what would be a good way to configure this? via env vars?

Either that, or with a configmap like [1], @hasbro17 do we have a preferred method for allowing configuration like this?

[1] https://github.com/openshift/cluster-etcd-operator/blob/master/pkg/operator/defragcontroller/defragcontroller.go#L96

**Comment by tjungblu** [comment]
@dusk125 wdyt of adding this to the [RFE-2799](https://issues.redhat.com/browse/RFE-2799)? I reckon we can add this into a CRD as well.

**Pull request merged**
