### PR TITLE
[release-4.11] Bug 2108595: Cherrypick move etcd monitoring dashboard…

### PR DESCRIPTION
**Pull request by Elbehery**
This PR is a manual cherry pick from https://github.com/openshift/cluster-etcd-operator/pull/837

### CODE REVIEW

**Review by geliu2016 — APPROVED** [review]
/lgtm 
/label cherry-pick-approved

**Comment by deads2k** [comment]
GA is slated for 8/13, this PR is a medium BZ that appears to be non-blocker.  Is it more severe than it seems or can we wait until 4.11.1?

**Comment by Elbehery** [comment]
> GA is slated for 8/13, this PR is a medium BZ that appears to be non-blocker. Is it more severe than it seems or can we wait until 4.11.1?

it is not severe, we can wait

**Pull request merged**
