### PR TITLE
Bug 1826724: Fix openshift_etcd_operator_build_info metric

### PR DESCRIPTION
**Pull request by mfojtik**

### CODE REVIEW

**Comment by alaypatel07** [comment]
dug a little into https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_cluster-etcd-operator/311/pull-ci-openshift-cluster-etcd-operator-master-e2e-gcp/1173

CEO bootstrapped successfully, etcd is healthy. I found etcd-bootstrap member remove event[1] and co/etcd status[2] as expected.

1. https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_cluster-etcd-operator/311/pull-ci-openshift-cluster-etcd-operator-master-e2e-gcp/1173/artifacts/e2e-gcp/events.json
2. https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_cluster-etcd-operator/311/pull-ci-openshift-cluster-etcd-operator-master-e2e-gcp/1173/artifacts/e2e-gcp/clusteroperators.json

**Comment by hexfusion** [comment]
> the server is currently unable to handle the request (get imagestreams.image.openshift.io pipeline
 flakes

/retest

**Comment by mfojtik** [comment]
/retest

azure flakz

**Comment by mfojtik** [comment]
fixed conflict in go.mod, reapplying lgtm label.

**Pull request merged**
