### PR TITLE
[4.11] OCPBUGS-2919: update prometheus alerts

### PR DESCRIPTION
**Pull request by tjungblu**

### CODE REVIEW

**Comment by Elbehery** [comment]
That's gr88 .. actually i thought it does not work because the version of the etcd, did it :)

**Comment by tjungblu** [comment]
> That's gr88 .. actually i thought it does not work because the version of the etcd, did it :)

@Elbehery aside from openshift 4.8, everything above is on 3.5.5, that's what we recently rebased towards if you remember.

**Comment by tjungblu** [comment]
@geliu2016 I'd also need a CPA here please :pray: :)

**Review by geliu2016 — APPROVED** [review]
/label cherry-pick-approved

**Pull request merged**
