### PR TITLE
OCPBUGS-7198: [release-4.8] Rotate serving certs when duration less than minimum percent

### PR DESCRIPTION
**Pull request by gogeof**
Follow #606 

For some reason，we can't update cluster version to 4.9, and the etcd cert will expired soon, so we hope that etcd operator support update cert autolly, like 4.9.

### CODE REVIEW

**Comment by tjungblu** [comment]
/ok-to-test

@hasbro17 wdyt?

**Comment by tjungblu** [comment]
(my2cents)

for me it's fine to backport, but there won't be another z release of 4.8 in the calendar AFAIK, so I'm curious how you want to get this to customers?

**Comment by gogeof** [comment]
> 

there won't be another z release of 4.8?  Maybe could be one more z release because of 4.8 is in " Maintenance support " before February 3 , 2023 .  :)

**Comment by tjungblu** [comment]
I don't see another one scheduled on the calendar, but maybe it's not updated for the new year just yet :)

**Comment by gogeof** [comment]
@tjungblu 😭

**Comment by gogeof** [comment]
@tjungblu Could you executive /retest again ?

**Comment by dusk125** [comment]
> (my2cents)
> 
> for me it's fine to backport, but there won't be another z release of 4.8 in the calendar AFAIK, so I'm curious how you want to get this to customers?
> 
> > @dusk125 wdyt?

So we can't guarantee that this will ever show up in a release; it's possible that it would be included with security fixes later on, but we can't say for certain when, or if, that would occur. As long as everyone is ok with that, we can continue this forward.

**Comment by gogeof** [comment]
👌，wait for your good news!

/assign @dusk125

**Comment by gogeof** [comment]
@dusk125 Sorry to bother you again，it seems also need bugzilla/valid-bug, cherry-pick-approved labels.

**Comment by dusk125** [comment]
@geliu2016 when you get a chance, could you review this please?

**Comment by geliu2016** [comment]
> @geliu2016 when you get a chance, could you review this for cherry-pick-approved please?

lgtm as code changing itself, and I curious is there available workaround if cert have been expired in customer's env? or it recommend customer install this 4.8 z release to bypass the cert expiring issue, thanks

**Comment by gogeof** [comment]
@geliu2016 @dusk125 need bugzilla/valid-bug label :)

**Comment by gogeof** [comment]
> > @geliu2016 when you get a chance, could you review this for cherry-pick-approved please?
> 
> lgtm as code changing itself, and I curious is there available workaround if cert have been expired in customer's env? or it recommend customer install this 4.8 z release to bypass the cert expiring issue, thanks

and if you could support this, it's better!

**Comment by gogeof** [comment]
@dusk125 Please run /retest again for my mistake to close and reopen this PR again.

**Comment by tjungblu** [comment]
/retitle OCPBUGS-7198: [release-4.8] Rotate serving certs when duration less than minimum percent

**Comment by tjungblu** [comment]
@gogeof what are we going to do with this? Given that 4.8 is out of support officially for more than a month and it should only release urgent security fixes going forward... Build seems broken as well :/

Is there any way we can help with the upgrade path to 4.10 maybe?

**Comment by gogeof** [comment]
> @gogeof what are we going to do with this? Given that 4.8 is out of support officially for more than a month and it should only release urgent security fixes going forward... Build seems broken as well :/
> 
> Is there any way we can help with the upgrade path to 4.10 maybe?

thanks a lot, we can upgrade cluster to 4.10, do you have any experience or FAQ for reference about 4.8 to 4.10?

**Comment by tjungblu** [comment]
> thanks a lot, we can upgrade cluster to 4.10, do you have any experience or FAQ for reference about 4.8 to 4.10?

@gogeof unfortunately nothing specific. I believe the path would still be 4.8 -> 4.9 -> 4.10. Do you see such a path in your cluster console?

**Comment by gogeof** [comment]
> > thanks a lot, we can upgrade cluster to 4.10, do you have any experience or FAQ for reference about 4.8 to 4.10?
> 
> @gogeof unfortunately nothing specific. I believe the path would still be 4.8 -> 4.9 -> 4.10. Do you see such a path in your cluster console?

yes, it's ok, thanks for help.

**Pull request closed without merging**
