### PR TITLE
bug 1805519: Merge master into release-4.4

### PR DESCRIPTION
**Pull request by sanchezl**
bug 1801938: add host-etcd-2 which will never list the bootstrap etcd as an endpoi…
bug 1805421: allow bootstrap server to terminate before removing etcd-bootstrap fr…

### CODE REVIEW

**Comment by deads2k** [comment]
https://github.com/openshift/cluster-kube-apiserver-operator/pull/774 must merge first

/lgtm
/hold

release hold when the other has merged

**Comment by hexfusion** [comment]
https://github.com/openshift/cluster-kube-apiserver-operator/pull/774 has merged

/hold cancel
/retest

**Pull request merged**
