### PR TITLE
bug 1801397: static pod manager

### PR DESCRIPTION
**Pull request by deads2k**
Adds a static pod manager.  The test has been updated, we've seen green upgrades and green installs (minus the test update) in https://github.com/openshift/cluster-etcd-operator/pull/112. 

This starts a new testing history

### CODE REVIEW

**Comment by deads2k** [comment]
Upgrade stuck on machineconfigpool 
/retest

**Comment by deads2k** [comment]
alert flake

/retest

**Comment by hexfusion** [comment]
Great work to all involved, thank you @deads2k @alaypatel07 @sanchezl !
/lgtm

**Comment by deads2k** [comment]
https://github.com/openshift/machine-config-operator/pull/1473 bites again

/test all

**Comment by hexfusion** [comment]
gcp flake 

/retest

**Comment by deads2k** [comment]
Alerts
/Retest

**Comment by alaypatel07** [comment]
https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_cluster-etcd-operator/112/pull-ci-openshift-cluster-etcd-operator-master-e2e-azure/512

FTR for this azure run CEO was reporting healthy. 
```
                "conditions": [
                    {
                        "lastTransitionTime": "2020-02-14T03:51:40Z",
                        "message": "NodeControllerDegraded: All master nodes are ready",
                        "reason": "AsExpected",
                        "status": "False",
                        "type": "Degraded"
                    },
                    {
                        "lastTransitionTime": "2020-02-14T03:52:46Z",
                        "message": "NodeInstallerProgressing: 3 nodes are at revision 2\nEtcdMembersProgressing: no unstarted members found\nClusterMemberControllerScalingProgressing: Scaling etcd membership completed",
                        "reason": "AsExpected",
                        "status": "False",
                        "type": "Progressing"
                    },
                    {
                        "lastTransitionTime": "2020-02-14T03:50:16Z",
                        "message": "StaticPodsAvailable: 3 nodes are active; 3 nodes are at revision 2\nEtcdMembersAvailable: ci-op-gt4s0rxg-52597-j4755-master-1,ci-op-gt4s0rxg-52597-j4755-master-0,ci-op-gt4s0rxg-52597-j4755-master-2 members are available,  have not started,  are unhealthy",
                        "reason": "AsExpected",
                        "status": "True",
                        "type": "Available"
                    },
                    {
                        "lastTransitionTime": "2020-02-14T03:45:37Z",
                        "reason": "AsExpected",
                        "status": "True",
                        "type": "Upgradeable"
                    }
                ],
```
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_cluster-etcd-operator/112/pull-ci-openshift-cluster-etcd-operator-master-e2e-azure/512/artifacts/e2e-azure/clusteroperators.json

**Comment by deads2k** [comment]
azure appears to consistently fail on the same monitor cannot rollout capacity issue we had everywhere early this week.

The upgrade job is failing because the machine-config-pool is conflicting

**Comment by retroflexer** [comment]
Vanilla install (no upgrade) with this PR and mco-1465 is successful!

**Comment by hexfusion** [comment]
https://github.com/openshift/origin/pull/24547

Should fix CI failures

**Comment by hexfusion** [comment]
/hold

we need to figure out a little more with upgrades.

**Pull request closed without merging**
