### PR TITLE
OCPBUGS-17199:  Revert pull request https://github.com/openshift/cluster-etcd-operator/issues/1350

### PR DESCRIPTION
**Pull request by dusk125**
…eck"

This reverts commit 28467760b688785bf62a463b5ba545892cbd9471, reversing changes made to 52cac6a07da30a239e370311fac9052ba393505a.

### CODE REVIEW

**Comment by dusk125** [comment]
/payload-job periodic-ci-openshift-cluster-control-plane-machine-set-operator-release-4.18-periodics-e2e-aws

**Comment by dusk125** [comment]
/payload-aggregate periodic-ci-openshift-cluster-control-plane-machine-set-operator-release-4.18-periodics-e2e-aws 10

**Comment by hasbro17** [comment]
Build failures
https://prow.ci.openshift.org/view/gs/test-platform-results/logs/aggregator-periodic-ci-openshift-cluster-control-plane-machine-set-operator-release-4.18-periodics-e2e-aws/1845851918572720128
```
 [36mINFO[0m[2024-10-14T15:39:37Z] Building release latest from a snapshot of ocp/4.18 
[36mINFO[0m[2024-10-14T15:39:37Z] Requesting a release from https://arm64.ocp.releases.ci.openshift.org/api/v1/releasestream/4.18.0-0.nightly-arm64/latest 
[36mINFO[0m[2024-10-14T15:39:37Z] Resolved release arm64-latest to registry.ci.openshift.org/ocp-arm64/release-arm64:4.18.0-0.nightly-arm64-2024-10-14-115031 
[36mINFO[0m[2024-10-14T15:39:37Z] Using namespace https://console-openshift-console.apps.build03.ky4t.p1.openshiftapps.com/k8s/cluster/projects/ci-op-pi1zq528 
[36mINFO[0m[2024-10-14T15:39:37Z] Ran for 0s                                   
[31mERRO[0m[2024-10-14T15:39:37Z] Some steps failed:                           
[31mERRO[0m[2024-10-14T15:39:37Z] 
  * could not sort nodes
  * steps are missing dependencies
  * step e2e-aws-0 is missing dependencies: <&api.internalImageStreamTagLink{name:"pipeline", tag:"src", unsatisfiableError:""}> 
[36mINFO[0m[2024-10-14T15:39:37Z] Reporting job state 'failed' with reason 'building_graph' 
[36mINFO[0m[2024-10-14T15:39:37Z] Reporting job state 'failed' with reason 'unknown' 
[36mINFO[0m[2024-10-14T15:39:37Z] Reporting job state 'failed' with reason 'unknown' 
```

Rerunning

/payload-job periodic-ci-openshift-cluster-control-plane-machine-set-operator-release-4.18-periodics-e2e-aws

**Comment by vrutkovs** [comment]
/retitle OCPBUGS-17199:  Revert pull request https://github.com/openshift/cluster-etcd-operator/issues/1350

**Comment by vrutkovs** [comment]
/hold cancel

This unblock cert-rotation tests

**Pull request merged**
