### PR TITLE
sanity?

### PR DESCRIPTION
**Pull request by hexfusion**
Signed-off-by: Sam Batschelet <sbatsche@redhat.com>

### CODE REVIEW

**Comment by lilic** [comment]
oops :(

**Comment by hexfusion** [comment]
yeah its proof we have some work to do ..

**Comment by lilic** [comment]
/retest

🤞

**Comment by hexfusion** [comment]
> INFO[2021-06-11T10:57:02Z] Acquired 1 lease(s) for gcp-quota-slice: [us-east1--gcp-quota-slice-31] 
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-etcd-operator/611/pull-ci-openshift-cluster-etcd-operator-master-e2e-agnostic-upgrade/1403303675639631872

**Pull request closed without merging**
