### PR TITLE
Bug 1806700: pkg/operator/targetconfigcontroller: add platform raft tunables

### PR DESCRIPTION
**Pull request by hexfusion**
We need the ability to adjust etcd runtimes based on provider type. In the future, we could consider autotuning these based on metrics.

### CODE REVIEW

**Comment by hexfusion** [comment]
> Throttling: Rate exceeded\n\tstatus code: 400
/retest

**Comment by hexfusion** [comment]
/hold
needs more work not top priority

**Comment by hexfusion** [comment]
> 2020-02-28 14:14:24.335299 I | pkg/flags: recognized and used environment variable ETCD_ELECTION_TIMEOUT=2500
2020-02-28 14:14:24.335313 I | pkg/flags: recognized and used environment variable ETCD_HEARTBEAT_INTERVAL=500

works for azure at least

**Comment by hexfusion** [comment]
>2020-02-28 14:07:33.429677 I | pkg/flags: recognized and used environment variable ETCD_ELECTION_TIMEOUT=1000
2020-02-28 14:07:33.429733 I | pkg/flags: recognized and used environment variable ETCD_HEARTBEAT_INTERVAL=100

gcp

**Comment by deads2k** [comment]
/lgtm

This looks reasonable.  Release your hold at will.

**Comment by hexfusion** [comment]
cc @smarterclayton @jim-minter

**Pull request merged**
