### PR TITLE
[release-4.10] OCPBUGS-7827: set default timeouts in etcdcli

### PR DESCRIPTION
**Pull request by lance5890**
[for ceo connection timeout](https://github.com/openshift/cluster-etcd-operator/issues/1000)

### CODE REVIEW

**Comment by tjungblu** [comment]
thanks @lance5890!

**Comment by tjungblu** [comment]
/retitle [release-4.10] OCPBUGS-7827: set default timeouts in etcdcli

**Comment by tjungblu** [comment]
okay, I guess the bot has a day off today. I'll check again tomorrow.

**Review by geliu2016 — APPROVED** [review]
/label cherry-pick-approved

**Comment by Elbehery** [comment]
@hasbro17 @dusk125  another override ?

**Comment by lance5890** [comment]
> @tjungblu: #1010 failed to apply on top of branch "release-4.9":
> 
> ```
> Applying: set default etcd client timeout
> Using index info to reconstruct a base tree...
> M	pkg/etcdcli/etcdcli.go
> A	pkg/etcdcli/etcdcli_pool.go
> Falling back to patching base and 3-way merge...
> CONFLICT (modify/delete): pkg/etcdcli/etcdcli_pool.go deleted in HEAD and modified in set default etcd client timeout. Version set default etcd client timeout of pkg/etcdcli/etcdcli_pool.go left in tree.
> Auto-merging pkg/etcdcli/etcdcli.go
> CONFLICT (content): Merge conflict in pkg/etcdcli/etcdcli.go
> error: Failed to merge in the changes.
> hint: Use 'git am --show-current-patch=diff' to see the failed patch
> Patch failed at 0001 set default etcd client timeout
> When you have resolved this problem, run "git am --continue".
> If you prefer to skip this patch, run "git am --skip" instead.
> To restore the original branch and stop patching, run "git am --abort".
> ```

@tjungblu

I wil commit a new PR in release-4.9

**Comment by Elbehery** [comment]
thanks a lot @lance5890

**Pull request merged**
